### ISSUE TITLE
Java: CWE-273 Unsafe certificate trust

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#102]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

The query checks a very common issue with web development - certificate trust manager is set to trust all certificates or the hostname verifier is turned off. 

Java offers two mechanisms for SSL authentication - trust manager and hostname verifier. Trust manager validates the peer's certificate chain while hostname verification establishes that the hostname in the URL matches the hostname in the server's identification.

Unsafe implementation of the interface X509TrustManager and HostnameVerifier ignores all SSL certificate validation errors when establishing an HTTPS connection, thereby making the app vulnerable to man-in-the-middle attacks.

I've tested it against some GitHub projects, and a test case has been created to facilitate auto-testing. The relevant PR is [PR #3550](https://github.com/github/codeql/pull/3550).

- [Yes] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Created Hackerone report 917454 for bounty 227491 : [102] Java: CWE-273 Unsafe certificate trust 🎉

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty.
