### ISSUE TITLE
Java: CWE-798 - Hardcoded AWS credentials

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#129]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Cloud services are being increasingly used in recent years, and AWS is one of the most popular service providers.

Authentication to AWS services, for example, the popular S3 cloud storage service, using the BasicAWSCredentials class of the Amazon client SDK library with hardcoded access key/secret key in Java code is against best practices and violates [CWE-798](https://cwe.mitre.org/data/definitions/798.html). 

Other [approaches](https://docs.amazonaws.cn/en_us/general/latest/gr/aws-access-keys-best-practices.html) offered by AWS including AWS credentials file, environment variables, or instance/container credentials are more secure thus shall be used instead.

For more information, please refer to the [AWS Developer Guide](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html).

Related PR [#3729](https://github.com/github/codeql/pull/3729)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by luchua-bc** [comment]
@xcorail As the PR of this issue was approved and closed about four weeks ago, would you please close this issue when you have a chance? Thanks in advance for your help.

@luchua-bc

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 956967 for bounty 237854 : [129] Java: CWE-798 - Hardcoded AWS credentials 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for looking into the issue and the quick turn-around.

@luchua-bc
