### ISSUE TITLE
[javascript] CWE-117: CodeQL query to detect Log Injection

### ISSUE THREAD

**Issue by dellalibera** [github/securitylab#130]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- There is no CVE for this.

## Report

Log Injection  is available in c# query but it is not available in Javascript query. 
I created a query to detect a log injection vulnerability in Javascript code.

- [X] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

Link to the now merged PR: [PR github/codeql#3734](https://github.com/github/codeql/pull/3734)

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- I was not able to find this issue in the projects I used for testing. However in the PR I added different examples scenarios.

In another PR [github/codeql#3823](https://github.com/github/codeql/pull/3823) I also added the support for another logging module to expand the support of logging calls, that could be helpful also for this query.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 963816 for bounty 239463 : [130] [javascript] CWE-117: CodeQL query to detect Log Injection 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by dellalibera** [comment]
Thanks @xcorail for the bounty!!
