### ISSUE TITLE
[javascript] CWE-347: JWT Missing Secret Or Public Key Verification

### ISSUE THREAD

**Issue by toufik-airane** [github/securitylab#133]
# CVE ID(s)

- N/A

# Report

The featured CodeQL query warns using of none algorithm in verify() functions imported from jsonwebtoken package developed by the auth0 organization.
- https://www.npmjs.com/package/jsonwebtoken
- https://github.com/auth0/node-jsonwebtoken

JavaScript applications handling JWT could be affected by a well-known misconfiguration due to the misuse of the none algorithm.
- https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/#Meet-the--None--Algorithm
- https://tools.ietf.org/html/rfc7519#section-6.1

Indeed, the _jsonwebtoken_ package developed by the Auth0 company specifies that the **none algorithm doesn't enforce digital signature** and It's a feature. In that scenario, **providing the value _false_ instead of a secret or a key will decode the JWT without signature verification**.
- https://www.npmjs.com/package/jsonwebtoken

A secure coding framework requires auditable and automated security measures to ensure good practices in codebases.
By running the featured CodeQL query, you ensure that calling `verify()` functions always take a secret or a key to decode JWT payloads.

# Resource
- Issue: https://github.com/github/securitylab/issues/133
- PR: https://github.com/github/codeql/pull/3751

[X] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

# Result(s)

I would be happy to run the query on a list of repositories if you can help me figure out how to get an insightful list.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by anticomputer** [comment]
Hi @toufik-airane 

Your query submission for the All For One bounty is currently in review. One of the stipulations of eligibility is that the query should detect at least 1 TP on a real project (current or previous version).

We ran your query across LGTM and were unable to detect a TP in the current project set available on LGTM, but if you can provide an example of an affected project (even if it a prior version) that your query will alert a TP on, we will be able to move the review process forward.

Please let us know if you can provide such an example.

**Comment by toufik-airane** [comment]
Dear,

I don't have any open source sample to provide, sorry.

**Comment by anticomputer** [comment]
> Dear @anticomputer,
> 
> I don't have any open source sample to provide, sorry.

@toufik-airane unfortunately that means the submission is currently not eligible for a bounty award under the "All For One" category. We do think it's a great query and important issue, so if you do come across a project that will meet these requirement please feel free tag me in a comment here and I will re-open the issue so we can move this forward in the bounty review process.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
