### ISSUE TITLE
Java: Detect remote source from Android intent extra

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#140]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Android uses the IPC (Inter Process Communication) mechanism for communications among difference applications and different application components. The most common system functionality for IPC is Intent. Android allows a wide range of data types to be passed as intent extras. 

Exported Android components including activities, services, receivers, and providers can be invoked by other applications on the same mobile device thus expose the attack surface. Android Activities, services, and receivers can be exposed in two ways:
+ Explicitly set `android:exported` to true
+ Set intent filters without `android:exported` explicitly set to false

The second scenario is very important and issues in this category are very common in Android applications.

Also please note not all intent data passed between Android components impose security concerns - intent data passed between internal components of the same application, which cannot be controlled by attackers, shall not be treated as remote source. This helps to eliminate a large amount of false positives.

The related PR is [#3812](https://github.com/github/codeql/pull/3812), which addresses the following two issues:
+ Enhance the Android library `Android.qll` and `AndroidManifest.qll` to handle the second scenario with intent filters
+ Implement a remote source for Android intent extra

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*
As the relevant PR enhances the core library, there is no accompanying query to run against real projects. Security researchers including myself can use the new remote source of Android intent extra as entry points to detect various security vulnerabilities in real Android projects. I will submit PRs for specific CWE vulnerability types in separate reports.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
As the relevant PR [#3812](https://github.com/github/codeql/pull/3812) has already been merged into main and closed, could the status of this issue be updated as well?

Thanks,
@luchua-bc

**Comment by xcorail** [comment]
Hey @luchua-bc the team is currently scoring your submission. We are taking some time to align our jury :)
Thanks for your patience!

**Comment by luchua-bc** [comment]
Thanks @xcorail for your prompt update. I understand this one is special since it changes the core library and updates the framework for all Android related queries.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1030295 for bounty 257529 : [140] Java: Detect remote source from Android intent extra 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail.
