### ISSUE TITLE
Java: CWE-522 Insecure basic authentication

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#161]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Basic authentication only obfuscates username/password in Base64 encoding, which can be easily recognized and reversed. And transmission of sensitive information not in HTTPS is vulnerable to interception by networking devices and packet sniffing.

Basic authentication is still widely used by many projects, and basic authentication over HTTP is a common vulnerability. Searching basic authentication over HTTP returns thousands of occurrences in public GitHub repositories. 

This query detects vulnerable implementations using the popular `java.net` library and the Apache HttpClient.

Related PR - [3976](https://github.com/github/codeql/pull/3976)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*
Four projects with this issue are:
- [OrangeCobras/TRAINsleeperBEEPER](https://github.com/OrangeCobras/TRAINsleeperBEEPER)
- [TinkerPhil/lcagdev](https://github.com/TinkerPhil/lcagdev)
- [heshuying/ylwds](https://github.com/heshuying/ylwds)
- [Apache/ambari](https://github.com/apache/ambari/pull/3210)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 963815 for bounty 239462 : [161] Java: CWE-522 Insecure basic authentication 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty.

@luchua-bc
