### ISSUE TITLE
[javascript] CWE-614: CodeQL query to detect if cookies are sent without the flag secure being set

### ISSUE THREAD

**Issue by dellalibera** [github/securitylab#169]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- There is no CVE for this.

## Report

Failing to set the secure flag on a cookie can cause it to be sent in clear text. This makes it easier for an attacker to intercept and read the cookie.

Query to detect if the `secure` flag is set to cookies is available in java query but it is not available in JavaScript query.
This query detects if cookies are sent without the flag secure being set or with the flag secure being set to false.

Link to the merged PR: [PR github/codeql#3978](https://github.com/github/codeql/pull/3978)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

The query was able to detect the following issues (now fixed):
|Issue | Fix|
|------|------|
|[ibm-dotcom-library/packages/utilities/src/utilities/ipcinfoCookie/ipcinfoCookie.js#L59](https://github.com/carbon-design-system/ibm-dotcom-library/blob/1adcd87c468aee159c4961f76f9d6084b7ce3956/packages/utilities/src/utilities/ipcinfoCookie/ipcinfoCookie.js#L59)|[ibm-dotcom-library/packages/utilities/src/utilities/ipcinfoCookie/ipcinfoCookie.js#L72](https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/utilities/src/utilities/ipcinfoCookie/ipcinfoCookie.js#L72)|
|[urly/server/routes/login.js#L32](https://github.com/nedzadalibegovic/urly/blob/aa99fde1528907764acedae06574ca3d333f3fb8/server/routes/login.js#L32)|[urly/server/routes/login.js#L54](https://github.com/nedzadalibegovic/urly/blob/master/server/routes/login.js#L54)|

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1053048 for bounty 263366 : [169] [javascript] CWE-614: CodeQL query to detect if cookies are sent without the flag secure being set
