### ISSUE TITLE
[javascript] CWE-90: CodeQL to detect LDAP Injection

### ISSUE THREAD

**Issue by dellalibera** [github/securitylab#170]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- There is no CVE for this.

## Report

Inspired by the amazing CodeQL query to detect LDAP Injection in Java, this query detects LDAP Injection in JavaScript using the NodeJS library [`ldapjs`](https://github.com/ldapjs/node-ldapjs).

Link to the merged PR: [PR github/codeql#4118](https://github.com/github/codeql/pull/4118)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

This query was able to detect the LDAP Injection mentioned in the following HackerOne reports:
- [https://hackerone.com/reports/907311](https://hackerone.com/reports/907311)
- [https://hackerone.com/reports/906959](https://hackerone.com/reports/906959)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL Initial assessment**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by kevinbackhouse** [comment]
Hi @dellalibera: we ran your query over all the projects on LGTM and found a couple of projects that have results that look like true positives. Would you like me to share those results with you, so that you can report them to the project maintainers? If so, please could you drop me an email (kev@github.com) or contact me on the security lab slack? Thanks, Kev.

**Comment by dellalibera** [comment]
Hi @kevinbackhouse, thank you for the message. I contacted you a on the security lab slack.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
