### ISSUE TITLE
codeql-go: Expand Go standard library taint-tracking models to 63 packages, 554 models and 733 tests (from ~13 packages, ~103 models, ~50 tests)

### ISSUE THREAD

**Issue by gagliardetto** [github/securitylab#187]
## CVE ID(s)

No CVE IDs for now.

## Report

Many CodeQL queries use *taint-flow tracking* in their logic. That allows them to track the movement (step by step) of data in the code from one point (a `source`) to another (a `sink`).

But taint-tracking is only as good as the number of taint-tracking **models we have** (i.e. the steps).

We could miss an **XSS** or **SQL-injection** in a widely-used app just because of a **missing taint-tracking model**.

For that reason, I decided to **expand the base of models** that existing and new queries will stand upon.

To do that, I built a **graphical tool** to speed up the process of creating the models: https://github.com/gagliardetto/codebox

(Here's what the (web) interface looks like:)

![codebox_screenshot](https://user-images.githubusercontent.com/15271561/86345187-e2bc5900-bc63-11ea-95e5-5f5e63e7040f.png)

After **25 PRs** into [codeql-go](https://github.com/github/codeql-go) (all merged), now the Go standard library taint-tracking covers _**63 packages**_, with _**554 models**_ and _**733 tests**_. 

Previously, that was _**~13 packages**_, _**~103 models**_, and _**~50 tests**_.

See https://github.com/github/codeql-go/pull/167#issuecomment-654071379 for **the complete list of PRs** and packages covered in them.

---
#### Added libraries and tests:

Taint models: https://github.com/github/codeql-go/tree/main/ql/src/semmle/go/frameworks/stdlib

Tests: https://github.com/github/codeql-go/tree/main/ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow

Imports: https://github.com/github/codeql-go/blob/main/ql/src/semmle/go/frameworks/Stdlib.qll#L6-L65

---

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

No, I'm not planning to discuss this vulnerability submission publicly.

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

To have a complete assessment of the impact of the new models, we would need to run the **complete suite of codelq queries** on all the Go projects known to lgtm.com. That's a challenge.

Until that can be done, @smowton kindly run some partial lgtm.com-compare for the `reflected-XSS` query with a few batches of the new models: See https://github.com/github/codeql-go/pull/347#issuecomment-697381047 for the **new results** that were found:

![screenshot_comment](https://user-images.githubusercontent.com/15271561/96175103-0d8c9d80-0f33-11eb-8618-03e8fecde4b3.png)

And that's the **result improvement** for just for **one** query.

**Comment by JLLeitschuh** [comment]
That's pretty impressive! 👏

**Comment by gagliardetto** [comment]
Thanks @JLLeitschuh ! That's just the beginning. I've got some more automation designs of this kind.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by kevinbackhouse** [comment]
Awesome work @gagliardetto! I have just completed the SecLab review and will pass it onto the next stage.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by gagliardetto** [comment]
Thank you @kevinbackhouse !

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
