### ISSUE TITLE
[Java] CWE-927: Sensitive broadcast 

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#192]
## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

It is a vulnerability if an Android application uses an implicit intent for transmitting sensitive data to other applications. Since an implicit intent does not specify a particular application to receive the data, any application can process the intent by using an Intent Filter for that intent. This allows untrusted applications to obtain sensitive data or causes denial of service attacks when ordered broadcasts are used.

I've tested the query against some open-source software on GitHub.

Relevant PR: [#4512](https://github.com/github/codeql/pull/4512)

 
- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

Two of many projects with this issue on GitHub are:
- [Languru](https://github.com/mrhoangmai93/CSIS4270-Special-topic)
- [jw_android](https://github.com/ChangeKiss/Store)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Thanks for the submission @luchua-bc 
We were discussing internally about the keywords used for the sensitiveness regexps and wondering if `userid` and `username` could have a low SNR. Have you encountered interesting cases where these values were really sensitive?

**Comment by luchua-bc** [comment]
<code>userid</code> and <code>username</code> could contain sensitive information e.g. when they are the same as email address or contain full name (first name and last name). Having said that, they are not particularly sensitive like password and access token.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1026252 for bounty 256678 : [192] [Java] CWE-927: Sensitive broadcast 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty:-)
