### ISSUE TITLE
[Java] CWE-755: Query to detect Local Android DoS caused by NFE

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#199]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

NumberFormatException (NFE) thrown but not caught by an Android application will crash the application. For  applications allowing external inputs, an attacker can send an invalid number as intent extra to trigger NFE, which introduces local Denial of Service (Dos) attack.

This is a very common problem in Android development since Android components don't have throw Exception(...) in their class and method definitions thus developers tend to follow the same pattern and leave this exception unprocessed.

To address this issue, either use the Android methods intended to get number extras e.g. <code>Intent.getFloatExtra(String name, float defaultValue)</code> since they have the built-in try/catch processing, or explicitly do try/catch in the application.

Relevant PR: [#4610](https://github.com/github/codeql/pull/4610)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*
- [taitocode/form-android](https://github.com/taitocode/form-android/pull/1)

By sending an invalid number like "a" for the input parameter "YYYY" to the application, the application will crash. A screenshot is as follows:
<img src="https://user-images.githubusercontent.com/37377780/98442911-f6764100-20d5-11eb-8c01-4a7a0a195801.png" width="50%" height="50%" />

- [demetere/project Showing Cars](https://github.com/demetere/project/issues/1)

By sending an invalid input like "abc" for the input parameter of "priceMin" to the application, the application will crash and a screenshot is as follows:
<img src="https://user-images.githubusercontent.com/37377780/98199190-a5f5bc80-1ef8-11eb-9337-bb7b3adcb42c.png" height="50%" width="50%" />

**Comment by intrigus-lgtm** [comment]
The linked project does not exist.
>   www.github.com/demetere/project for showing cars

**Comment by luchua-bc** [comment]
I did test the link before I submitted this issue. It seems that the repository for the linked project was deleted by the owner or converted to a private repository.

I will run the query to find another project then add the link.

**Comment by luchua-bc** [comment]
@intrigus-lgtm I've added another project [taitocode/form-android](https://github.com/taitocode/form-android).

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1061211 for bounty 266597 : [199] [Java] CWE-755: Query to detect Local Android DoS caused by NFE

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty.
