### ISSUE TITLE
CPP: CWE-191 into experimental this reveals a dangerous comparison

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#208]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*
The code compares the unsigned difference with zero.  It is highly probable that the condition is wrong if the difference expression has the unsigned type.  The condition holds in all the cases when difference is not equal to zero. It means that we may use condition not equal. But the programmer probably wanted to compare the difference of elements. 
This error occurs quite often and can have consequences when working with memory, when the size of a piece is calculated as a difference.
https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules
Relevant PR: https://github.com/github/codeql/pull/4745
- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [bug fix in openssl](https://github.com/openssl/openssl/pull/13515)  
- [bug fix in gnutls](https://gitlab.com/gnutls/gnutls/-/merge_requests/1364)

**Comment by ihsinme** [comment]
good afternoon. I ended up improving my query.

**Comment by ihsinme** [comment]
good afternoon.
please tell me what should i do?

**Comment by jbj** [comment]
Are you done with the query for the purpose of the bounty programme? Maybe you already indicated that, but it wasn't completely clear to me. From https://securitylab.github.com/bounties:
> Queries must meet at least the requirements for [experimental queries](https://github.com/github/codeql/blob/main/CONTRIBUTING.md), [...]. Higher bounties will be awarded for queries that also meet additional requirements for [supported queries](https://github.com/github/codeql/blob/main/docs/supported-queries.md), including query help and tests.

So to be totally clear: would you like Security Lab to consider your query for a bounty now?

**Comment by ihsinme** [comment]
> So to be totally clear: would you like Security Lab to consider your query for a bounty now?
Yes

**Comment by jbj** [comment]
Ping @xcorail: do you have all you need to do the Security Lab assessment?

**Comment by xcorail** [comment]
@jbj yes, please provide a LGTM run and  move the internal issue to the SecLab review phase. Thanks!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
👋🏾 @ihsinme can you please send me privately an email address to claim your bounty? Thanks

**Comment by ihsinme** [comment]
I sent you an email at xcorail@github.com

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1065401 for bounty 267736 : [208] CPP: CWE-191 into experimental this reveals a dangerous comparison

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
Thank you.
