### ISSUE TITLE
[Java] CWE-327: Add more broken crypto algorithms

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#216]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*
Using broken or weak cryptographic algorithms can leave data vulnerable to being decrypted.

The ECB encryption mode is vulnerable to replay attacks and the CBC mode of operation with PKCS#5 (or PKCS#7) padding is vulnerable to padding oracle attacks. These two types of algorithms are widely treated as insecure/broken cryptographic algorithms in modern standards. There are hundreds of GitHub repositories that are still using these broken algorithms.

Some references are:
1. [Test cases for risky or broken cryptographic algorithm erroneously labeled as not vulnerable #92](https://github.com/OWASP/Benchmark/issues/92) - OWASP Test Cases
2. [codeql/csharp/ql/src/Security Features/Encryption using ECB.ql](https://github.com/github/codeql/blob/8d4f7e2db7ec3b7559a3e358fd1b8a7203ce7474/csharp/ql/src/Security%20Features/Encryption%20using%20ECB.ql) - C# Query for Encryption using ECB
3. [AES encryption algorithm should be used with secured mode](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4432) - SonarSource Rule RSPEC-4432
4. [CWE-327](https://cwe.mitre.org/data/definitions/327.html) - Use of a Broken or Risky Cryptographic Algorithm

This query adds these two categories to the list of insecure ciphers so that CodeQL can detect them.

Relevant PR - [#4833](https://github.com/github/codeql/pull/4833)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*
- [Tron Wallet](https://github.com/zx63/TronWallet)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1123360 for bounty 282599 : [216] [Java] CWE-327: Add more broken crypto algorithms

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty:-)
