### ISSUE TITLE
[Java] CWE-598: Use of GET Request Method with Sensitive Query Strings

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#223]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

When an application uses the GET method to submit sensitive information such as passwords and access tokens, it is transmitted within the query string of the requested URL. Sensitive information within URLs may be logged in various locations, including the user's browser, the web server, and any forward or reverse proxy servers between the two endpoints. URLs may also be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third parties via the Referer header when any off-site links are followed. Placing passwords into the URL therefore increases the risk that they will be captured by an attacker.

This kind of vulnerabilities is categorized as CWE-598: Use of GET Request Method with Sensitive Query Strings.

This query detects GET requests with sensitive information handled by Java EE Servlets.

Relevant PR is [PR# 4880](https://github.com/github/codeql/pull/4880)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [yuanshangkui/yetdoing](https://github.com/yuanshangkui/yuanshangkui)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by m-y-mo** [comment]
@luchua-bc We've had an initial look at the results from your query. It seems that the query is currently flagging everything that comes from a `HttpRequest` instead of just the query string, which results in many false positives. It may be better to use `isRequestGetParamMethod` as a source instead. Would you be able to modify the query according and then we can take another look? Thanks.

**Comment by luchua-bc** [comment]
Thanks @m-y-mo for reviewing this issue. I've committed the change to use <code>isRequestGetParamMethod</code> as the source instead. Please review again.

**Comment by pwntester** [comment]
Hi @luchua-bc, the results look better now, but there are still too many FPs caused by the broad `getCommonSensitiveInfoRegex` predicate. I would suggest to reuse this predicate but exclude `^token$` and `^token.*` since it seems the TPs are in the form of `accessToken`, `authenticationToken`, `authToken`, ...

**Comment by luchua-bc** [comment]
Thanks @pwntester for reviewing this PR. I've made the requested change. Please review.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1122662 for bounty 282423 : [223] [Java] CWE-598: Use of GET Request Method with Sensitive Query Strings

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty:-)
