### ISSUE TITLE
porcupiney.hairs : Java/Android - Insecure Loading of a Dex File 

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#232]
## Report

Dex file loading is mostly used for providing a localised update functionality or a plugin loading functionality in the app. Loading a DEX library located in a world-readable/ writable directory can cause arbitary code execution vulnerabilities.

This query detects instances where a dexfile from a world readable/writable directory is loaded by the app. Since anyone can write into a world writable directory, the attacker may create a new apk/dex package with the target name and have the application load and execute malicious code.

## Result(s)

- [oversecured/ovaa](https://github.com/oversecured/ovaa/blob/fd6489dc1356d3edf1b6412601a7560f08822de3/app/src/main/java/oversecured/ovaa/OversecuredApplication.java#L49-L51)
- [reyhoo/collection](https://github.com/reyhoo/collection/blob/5cc0ab1b0596fd7eefb0bf755525c1cc4b8d1579/JavaRXDemo/opensdk/src/main/java/com/chinaums/opensdk/weex/plugin/PluginManager.java#L82-L84)

**Comment by porcupineyhairs** [comment]
Link to the PR : github/codeql#4947

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Hi @porcupineyhairs, thanks for the submission! Unfortunately the query as-is is not returning any results on LGTM except for the `ovaa` vulnerable in purpose application you mentioned. This may be caused by missing relevant sources or maybe the lack of relevant projects configured in LGTM. Can you provide some TPs in the form of LGTM queries so we can validate the value of the query.

**Comment by pwntester** [comment]
@porcupineyhairs 

Can you please provide some examples of OSS apps showing this behaviour?  

Pasting slack chat for reference here:

```
porcupiney hairs  3:12 PM
Hey, regarding the Dex class loading issue
There are multiple projects which are vulnerable to this class of vulnerabilities.
However,  most of them are failing to build on lgtm due to one reason or another.
Can you accept detections in the form of github search results?
Basically I would mark code snippets which should be detected provided the project could  be built properly.

pwntester:github:  3:29 PM
yep sure. we just need some evidences that the query is going to provide value to Code Scanning and Enterprise users since otherwise it can be a waste of resources

porcupiney hairs  3:30 PM
To be clear, the query should detect it but it won't work on lgtm because the project does not build.

pwntester:github:  3:31 PM
got it and that should be ok. you can try to build it locally as well and then provide the database if you get it working

porcupiney hairs  3:31 PM
That seems reasonable. Give me some time I will share the details soon.
In general, how many tp's do you require?
Considering I would have to manually build and debug every single one mysel
I would just do the minimum required :sweat_smile:

pwntester:github:  3:33 PM
That is not carved in stone, to me a couple of them should be enough

porcupiney hairs  3:33 PM
Done. I will update you on this soon.

pwntester:github:  3:33 PM
but if these are student projects or damn vulnerable apps, we may need some more realistic examples
cool, thanks!

porcupiney hairs  3:35 PM
Nope they don't look like damn vuln apps. Some of them are re'd apps though
```

**Comment by smowton** [comment]
Re-eval since the author said he'd added more sinks: https://lgtm.com/query/2139286276875560535/

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1161956 for bounty 294619 : [232] porcupiney.hairs : Java/Android - Insecure Loading of a Dex File

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
