### ISSUE TITLE
CodeQL query for finding CSRF vulnerabilities in Spring applications

### ISSUE THREAD

**Issue by ggolawski** [github/securitylab#24]
## CVE ID(s)

There's no CVE for this.

## Report

Spring has built-in CSRF protection. However, it's possible to disable it, which most likely makes the application vulnerable to Cross-Site Request Forgery (CWE-352).

Spring CSRF protection can be disabled via Java configuration (more details [here](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-csrf-configure-disable)):

```java
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
  @Override
  protected void configure(HttpSecurity http) {
    http
      .csrf(csrf ->
        csrf.disable()
      );
  }
}
```

I created a CodeQL check (https://github.com/Semmle/ql/pull/2586) which finds all invocations of `CsrfConfigurer.disable()` method.

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Hey @ggolawski congratulations! 
Can you please DM us (Twitter @GHSecurityLab) your email address for the payment order?

**Comment by ggolawski** [comment]
Thanks @xcorail.
I sent you my email address via Twitter DM.

**Comment by xcorail** [comment]
Payment order sent 💰
