### ISSUE TITLE
Java: CWE-652 Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')

### ISSUE THREAD

**Issue by haby0** [github/securitylab#241]
## CVE

There is no CVE for this.

## Report

This query add XQuery Injection sinks.

```java
String name = request.getParameter("name");
XQDataSource ds = new SaxonXQDataSource();
XQConnection conn = ds.getConnection();
String query = "for $user in doc(\"users.xml\")/Users/User[name='" + name + "'] return $user/password";
XQPreparedExpression xqpe = conn.prepareExpression(query);
XQResultSequence result = xqpe.executeQuery();
```
Added CWE-652.

please check:

codeql/java/ql/src/Security/CWE/CWE-652/*

## Result(s)

- Link to the PR: [https://github.com/github/codeql/pull/4994](https://github.com/github/codeql/pull/4994)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
I would like to consult you about the next review process of CODEQL, because I see the current state is SecLab Review.

**Comment by pwntester** [comment]
Hi @haby0, thanks for the submission! Unfortunately the query as-is is not returning any results on LGTM. This may be caused by missing relevant sources/taint steps/sinks or maybe the lack of relevant projects configured in LGTM. Can you please provide some TPs in the form of LGTM queries so we can validate the value of the query.

**Comment by haby0** [comment]
Hi,Can I use the cases in the development project and my own test cases as LGTM queries?

**Comment by pwntester** [comment]
These should be real projects that prove that the vulnerability exists at least in one OSS project.

**Comment by haby0** [comment]
I found 472 places of use from github, I think it can be used as a reference. 
https://github.com/search?q=SaxonXQDataSource&type=code

**Comment by haby0** [comment]
Hi @pwntester ,Is there anything else I need to do?

**Comment by pwntester** [comment]
That example could be vulnerable if untrusted data reaches `XQExpression.executeQuery(0)` sink but your query does not seem to be accounting for that at the moment, so that may be the reason we are not getting any results.

**Comment by haby0** [comment]
@pwntester  Sorry, I made a mistake. The code for this project is different from mine. Because the `executeQuery` method of the `XQPreparedExpression` interface class does not receive parameters. I have no problem with ql here. At least when we checked the code of our company's project, we found a loophole.
Please refer to
https://www.freebuf.com/column/219966.html
https://github.com/haby0/v2/blob/master/src/main/java/com/vuln/v2/controller/XQueryInjection.java

**Comment by pwntester** [comment]
Note that `XQExpression` is a different class from `XQPreparedExpression`. It makes sense that the latter takes no arguments, but the former one does. You can try extending your query to also account for not prepared expressions.

**Comment by haby0** [comment]
Thanks, I researched ```XQExpression```.

**Comment by haby0** [comment]
Thanks @pwntester ,I've made the requested change. Please review.

**Comment by pwntester** [comment]
Awesome, thanks for the quick turnaround. From the docs, there is another method that stands out: [`executeCommand`](https://www.saxonica.com/documentation9.0/javadoc/net/sf/saxon/javax/xml/xquery/XQExpression.html#executeCommand(java.lang.String)) which I think should also be considered as a XQuery injection sink. Can you please evaluate it and add it to your query if appropriate?

**Comment by haby0** [comment]
Hi @pwntester , I searched the source code of saxon, saxon-dom, saxon-xpath, saxon-xqj and github. I found that the ```SaxonXQExpression``` class implements the ```XQExpression``` interface, and rewrites the ```executeCommand``` Method, but this method does not trigger XQuery injection. So I think there is no need to add to XQuery injection sink.
[SaxonXQExpression](https://www.saxonica.com/documentation9.0/javadoc/net/sf/saxon/xqj/SaxonXQExpression.html)
[SaxonXQExpression source code](https://github.com/jbosstools/jbosstools-locus/blob/665c442b646a5e1c2f86671d1be1614326eae92f/plugins/org.jboss.tools.locus.sf.saxon/9.2.1/src/net/sf/saxon/xqj/SaxonXQExpression.java)

**Comment by pwntester** [comment]
Interesting. I see there may be some implementations other than saxon that actually implement the `executeCommand` interface method: https://www.codota.com/code/java/methods/javax.xml.xquery.XQExpression/executeCommand

Since adding this sink will not create any FPs but can prevent some FNs I would prefer to add it.

**Comment by haby0** [comment]
Thanks,I will add sink as soon as possible.

**Comment by haby0** [comment]
Hi @pwntester , I added ```XQExpression.executeCommand(0)``` sink, please review.

**Comment by pwntester** [comment]
Thanks! will request a new run from the CodeQL team and get back to you as soon as possible

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
I wrote a blog of [detecting XQuery injection with CodeQL](https://github.com/haby0/mark/blob/master/articles/2021/Detecting%20XQuery%20injection%20with%20CodeQL.md), just for reference

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1133573 for bounty 285639 : [241] Java: CWE-652 Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
Thanks @xcorail for the quick turnaround and the bounty.
