### ISSUE TITLE
Java: Fix NashornScriptEngine detection in ScriptEngine query

### ISSUE THREAD

**Issue by p0wn4j** [github/securitylab#247]
## CVE ID(s)

There is no CVE for this.

## Report
Little fix in Java ScriptEngine detection query.

ScriptEngine query doesn't detect the cases where ScriptEngine is created by this way(using direct class as reference instead of using interface: NashornScriptEngine engine instead of ScriptEngine engine):
```
NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
NashornScriptEngine engine = (NashornScriptEngine) factory.getScriptEngine(...);
engine.eval(input);
```
In ScriptEngine.ql query:
```
class ScriptEngineMethod extends Method {
  ScriptEngineMethod() { 
    this.getDeclaringType().hasQualifiedName("javax.script", "ScriptEngine") and
    this.hasName("eval")
  }
}
```
If we just select ScriptEngineMethod
```
from ScriptEngineMethod s
select s, s.getDeclaringType()
```
We get only ScriptEngine interface methods:

1 | eval | ScriptEngine
2 | eval | ScriptEngine
3 | eval | ScriptEngine
4 | eval | ScriptEngine
5 | eval | ScriptEngine
6 | eval | ScriptEngine

When I change _this.getDeclaringType().hasQualifiedName("javax.script", "ScriptEngine")_ to _this.getDeclaringType().getASupertype*().hasQualifiedName("javax.script", "ScriptEngine")_ result changes to

1	eval	AbstractScriptEngine
2	eval	AbstractScriptEngine
3	eval	AbstractScriptEngine
4	eval	AbstractScriptEngine
5	eval	ScriptEngine
6	eval	ScriptEngine
7	eval	ScriptEngine
8	eval	ScriptEngine
9	eval	ScriptEngine
10	eval	ScriptEngine
11	eval	NashornScriptEngine
12	eval	NashornScriptEngine

There is a hierarchy: NashornScriptEngine --> AbstractScriptEngine --> ScriptEngine.
So I edited ScriptEngineMethod class in the query and add getASupertype*(). After change `predicate scriptEngine` can detect `engine.eval(input)` calls. Also can detect other custom written script engines' instantiations those are implementing ScriptEngine or extending AbstractScriptEngine.

```
class MyScriptEngine implements ScriptEngine { ... }

ScriptEngineManager scriptEngineManager = new ScriptEngineManager();
MyScriptEngine scriptEngine = (MyScriptEngine) scriptEngineManager.getEngineByExtension("js");
scriptEngine.eval(input);
```

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- Link to the PR: https://github.com/github/codeql/pull/5349

**Comment by kevinbackhouse** [comment]
Please could somebody run this on LGTM? Or would that not give us much information because it is an improvement to an existing query?

**Comment by kevinbackhouse** [comment]
Apologies, I meant to comment on the internal issue, not this one.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1121575 for bounty 282084 : [247] Java: Fix NashornScriptEngine detection in ScriptEngine query

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
