### ISSUE TITLE
Java: CWE-346 Queries to detect remote source flow to CORS Headers

### ISSUE THREAD

**Issue by torque59** [github/securitylab#248]
## CVE ID(s)

None. This is more like a bad security pattern being set. 

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

[Same origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) in browsers prevents, by default and for security-reasons, a javascript frontend to perform a cross-origin HTTP request to a resource that has a different origin (domain, protocol, or port) from its own. The requested target can append additional HTTP headers in response, called [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), that act like directives for the browser and change the access control policy / relax the same origin policy.

Computing this header value from information in the request to the server can therefore potentially allow an attacker to control,
the origins that the browser sends credentials to.

These types of issues are classified under [CWE-346: Origin Validation Error](https://cwe.mitre.org/data/definitions/346.html)

The query finds the following:
* `Access-Control-Allow-Origin` being set from a remote source flow along with `Access-Control-Allow-Credentials` set to true.

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [xuhuisheng/lemon](https://github.com/xuhuisheng/lemon)
- [shopizer-ecommerce/shopizer](https://github.com/shopizer-ecommerce/shopizer)

## Query
[github/codeql#5008](https://github.com/github/codeql/pull/5008)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Hi @torque59 thanks for the submission and sorry for the late response.

We have reviewed the initial set of results from your query and have found that in many cases there is some validation of the origin header being reflected. For example, the following projects contain FPs:

- uaarkoti/cors-filter
- SourceStudyNotes/Tomcat8
- dCache/dcache
- pentaho/pentaho-platform

At least the query should check if the origin header is checked against an array/list of allowed origins

**Comment by torque59** [comment]
@pwntester i have added a [sanitizer check](https://github.com/github/codeql/pull/5008/commits/409d95c5222a35e35f9d383f6021fd3472c3f963), which should ideally decrease some of the FP. 
Can you take a look at this and let me know, if this looks good ?

Btw this change was able to avoid FP in following only: 

- uaarkoti/cors-filter
- dCache/dcache
- pentaho/pentaho-platform

**Comment by pwntester** [comment]
Thanks, will request a new run and check what is the new rate of FPs

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1133574 for bounty 285640 : [248] Java: CWE-346 Queries to detect remote source flow to CORS Headers

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
