### ISSUE TITLE
[golang] Division by zero query

### ISSUE THREAD

**Issue by monkey-junkie** [github/securitylab#250]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- CWE-369 

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*
[Query](https://github.com/github/codeql-go/pull/442) adds detection for CWE-369: if integer variable from user input is zero and used as a divisor, it might lead to divide by zero and panic() in golang.
PR contains examples, tests documentation and actual query.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [Example repository with vulnerable revision of x/image/tiff of golang library](https://github.com/monkey-junkie/gogog3/), [lgtm.com scan](https://lgtm.com/query/4536962339793686645/) 
- Original vulnerability issue - https://github.com/golang/go/issues/10393

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Hey @monkey-junkie could you please provide a public email or privately send me one?

**Comment by monkey-junkie** [comment]
Hi!
Made my email public at https://github.com/monkey-junkie/
Thanks!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1102227 for bounty 277196 : [250] [golang] Division by zero query

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
