### ISSUE TITLE
ihsinme: CPP Add query for CWE-570 detect and handle memory allocation errors.

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#258]
## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*
In this query I am trying to find situations of incorrect handling of memory allocation using the new operator.
This error is quite common in projects and can lead to a violation of the logic of the program or to an unhandled crash.

of course, we can consider any selection without processing to be incorrect, but in this request I am considering exactly the situation of confusion. when the developer confused what kind of processing to apply. this allows us to understand that he tried to handle the case when the memory will not be allocated, but did not handle it correctly.
https://wiki.sei.cmu.edu/confluence/display/cplusplus/MEM52-CPP.+Detect+and+handle+memory+allocation+errors.  
Relevant PR: https://github.com/github/codeql/pull/5010  

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

https://github.com/google/sentencepiece/pull/581  
https://github.com/assimp/assimp/pull/3569

**Comment by ihsinme** [comment]
I do not plan to further improve the query.

**Comment by ihsinme** [comment]
this request of mine has been in a null state for a long time.
I'm worried why it doesn't go into the `CodeQL Initial assessment` state.
maybe I did something wrong?

**Comment by jbj** [comment]
Thanks for the ping. This issue fell between the cracks.

**Comment by kevinbackhouse** [comment]
@ihsinme: I was just looking through some results and noticed [this false positive result](https://lgtm.com/projects/g/gperftools/gperftools/snapshot/d4d31a89a3b899c623a633671b0d8e11514e16a8/files/src/stack_trace_table.cc?sort=name&dir=ASC&mode=heatmap#x54516536806ff3a3:1). Would that be easy to fix?

**Comment by ihsinme** [comment]
good day.
I looked at your example.
I think the complexity of the detection is that `getAChild` will return zero.
I may be wrong, but this is very similar to https://github.com/github/codeql/issues/4769.

I tried the `TemporaryObjectExpr` solution, but it didn't work.

I would love to hear your thoughts.

**Comment by kevinbackhouse** [comment]
I think this might be the correct way to identify calls to `new (std::nothrow) T[n]`:

```
import cpp

from FunctionCall call, Function f
where call.getTarget() = f
and f.hasGlobalOrStdName(["operator new", "operator new[]"])
and (f.isNoExcept() or f.isNoThrow())
select call, f
```

That's because my understanding of how the `nothrow` argument works is that it triggers a call to an overloaded version of `operator new` which is marked with `noexcept` or `throw()`.

@geoffw0: What do you think?

**Comment by ihsinme** [comment]
Good day.
your solution is definitely more elegant and better than the original. the only drawback is the need to simplify the test file.
but if it is acceptable, I am ready to form PR.

**Comment by geoffw0** [comment]
> @geoffw0: What do you think?

Yes I think that's cleaner and should be more accurate in practice.  We could also use `NewOrNewArrayExpr` in place of the name matching.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1161807 for bounty 294552 : [258] ihsinme: CPP Add query for CWE-570 detect and handle memory allocation errors.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
thanks
