### ISSUE TITLE
CodeQL query for finding LDAP Injection (CWE-90) vulnerabilities in Java

### ISSUE THREAD

**Issue by ggolawski** [github/securitylab#27]
## CVE ID(s)

There's no CVE for this.

## Report

I created a query to detect LDAP Injection vulnerabilities in Java (CWE-90). Plain JNDI, UnboundID, Spring LDAP and Apache LDAP API are covered.

The details including the complete list of covered APIs and classes (with examples) are present in PR: https://github.com/Semmle/ql/pull/2651

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by JLLeitschuh** [comment]
This is spectacular! Nice work!

**Comment by ggolawski** [comment]
Thanks. I guess I liked CodeQL :)

**Comment by xcorail** [comment]
Payment order reviewed and approved

**Comment by xcorail** [comment]
Payment order sent
Please @ggolawski can you confirm that you have received the emails from HackerOne?

![image](https://user-images.githubusercontent.com/7395402/73579031-87522900-4481-11ea-8d99-63ff3b152755.png)

**Comment by ggolawski** [comment]
Thanks, I've received both bounties :)
