### ISSUE TITLE
Java: JSONP Injection

### ISSUE THREAD

**Issue by haby0** [github/securitylab#277]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

When json is used as the transmission mechanism between the client and the server. When the server receives the function name requested by the client for splicing, the attacker may steal the possible confidential information transmitted from the server back to the client within the JSON object.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [lgtm query](https://lgtm.com/query/1280027726774420015/)
- [leiyi1152/shancai](https://github.com/leiyi1152/shancai)

**Comment by tamasvajk** [comment]
The corresponding codeql PR: https://github.com/github/codeql/pull/5206.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by anticomputer** [comment]
@JarLob @pwntester this would be considered JSONP injection rather than JSON hijacking no?

**Comment by anticomputer** [comment]
@haby0 hello I am reviewing your submission, question: we would consider your query to cover JSONP injection rather than JSON Hijacking no?

**Comment by haby0** [comment]
@anticomputer I have no opinion, please feel free to communicate if you have any questions.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
@anticomputer 

I improved the ql query. Mainly improved a few points.

1. Only accept the `doGet` request of the `Servlet` subclass, and the `get` request of the `SpringController` class. The requested data type is limited.

2. Fuzzy matching of remote `token`, `origin`, `Referer`, and `Auth` characters. If there is a check on them and the result is a boolean type, it is considered to be rejected.

3. For the verification of `origin`, I hope to use [CWE-346](https://github.com/github/securitylab/issues/248), which can be called directly in my checks method.

**Comment by haby0** [comment]
hi. Do I need to improve the pr in this request?

**Comment by anticomputer** [comment]
@haby0 your submission is currently in CodeQL team review, I have asked them for an update on their scoring and will move this along accordingly as soon as I hear back! Apologies for the wait

**Comment by haby0** [comment]
I wrote a blog post about [Detecting JSONP injection with CodeQL](https://github.com/haby0/mark/blob/master/articles/2021/Detecting%20JSONP%20injection%20with%20CodeQL.md).

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1175841 for bounty 297929 : [277] Java: JSONP Injection

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
@xcorail Thank you.
