### ISSUE TITLE
[Java] CWE-1004: Query to check sensitive cookies without the HttpOnly flag set 

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#292]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Cross-Site Scripting (XSS) has been a popular attack for many years, which is still ranked as one of the OWASP Top 10 Security Vulnerabilities 2020. Cookies holding sensitive information are vulnerable to XSS attacks if they don't have the HttpOnly flag set.

The HttpOnly flag directs compatible browsers to prevent client-side script from accessing cookies. Including the HttpOnly flag in the Set-Cookie HTTP response header for a sensitive cookie helps mitigate the risk associated with XSS where an attacker's script code attempts to read the contents of a cookie and exfiltrate information obtained.

The query detects all the common usage patterns that create sensitive cookies without the flag set using the Java EE framework. 

Relevant PR: [#5307](https://github.com/github/codeql/pull/5307)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [imcoder-blog](https://github.com/Jeffrey-deng/imcoder-blog)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by kevinbackhouse** [comment]
@luchua-bc: please could you explain the link to [imcoder-blog](https://github.com/Jeffrey-deng/imcoder-blog)? Did that repo have an example of this vulnerability?

**Comment by luchua-bc** [comment]
> @luchua-bc: please could you explain the link to [imcoder-blog](https://github.com/Jeffrey-deng/imcoder-blog)? Did that repo have an example of this vulnerability?

Hi @kevinbackhouse,

Thanks for reviewing this PR. Yes, that repo has an example of this vulnerability as shown in the issue I submitted to the repository owner [Issue #24: Sensitive cookie without the `HttpOnly` flag set](https://github.com/Jeffrey-deng/imcoder-blog/issues/24), which is in the program <code>src/main/java/site/imcoder/blog/Interceptor/LoginRequiredInterceptor.java</code>.

@luchua-bc

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1165198 for bounty 295240 : [292] [Java] CWE-1004: Query to check sensitive cookies without the HttpOnly flag set

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty.
