### ISSUE TITLE
Java: Non-Production interface

### ISSUE THREAD

**Issue by haby0** [github/securitylab#297]
## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

Attackers can use the legacy test interface in the production system to collect information or use functions that were otherwise unavailable. Non-production interfaces are insecure by default, and should not reside on the production system because they may leak sensitive information or functions of the system.

In addition, because many non-production interfaces are not intended to be used in a production environment, they do not have sufficient security controls or may not have undergone rigorous testing. Therefore, they may contain many flaws and loopholes, which may cause the adversary to seriously damage the target.

Relevant PR: [#5359](https://github.com/github/codeql/pull/5359)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result
- [lgtm](https://lgtm.com/query/4948394177021238052/)

**Comment by luchua-bc** [comment]
@haby0 Non-production interface/code are useful for testing functionalities of a codebase like unit testing and regression testing. And they are commonly adopted by a lot of projects as a best practice.

I think the code repository shall not be treated as a production environment, while the generated build is. If these test classes are removed from code repositories, projects cannot do their own tests.

They only raise a concern with the following two scenarios in my opinion:
- FPs with some queries so some CodeQL queries exclude test cases explicitly
- Test cases are included in production builds
It may be worthwhile checking the build tool (Maven, Ant, Gradle, etc.) together to only report test interfaces/classes that are included in the release build.

**Comment by haby0** [comment]
Thanks for the suggestion, this is very useful. ```forhaby0@gmail.com``` is my email, I hope we can communicate together.

**Comment by luchua-bc** [comment]
@haby0 You are welcome:). You may want to keep the discussion relevant to this PR here so that everyone is included in the loop. For discussions of a broader scope than this PR, you can start a thread in [GitHub Slack](https://ghsecuritylab.slack.com/ssb/redirect?entry_point=homepage_nav), many query developers including myself and CodeQL staff are actively watching it and can help to answer questions there. From my own experience, I've received high-quality answers to all my posts, which is very helpful.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
FYI I wrote a blog post about [Detecting Non-Production interface with CodeQL](https://github.com/haby0/mark/blob/master/articles/2021/Detecting%20Non-Production%20interface%20with%20CodeQL.md)

**Comment by xcorail** [comment]
Hey @haby0 cool! 
Please feel free to share your posts with the community (in Slack, or in https://github.com/github/securitylab#codeql-resources)

**Comment by haby0** [comment]
> Hey @haby0 cool!
> Please feel free to share your posts with the community (in Slack, or in https://github.com/github/securitylab#codeql-resources)

no problem.

**Comment by haby0** [comment]
@xcorail hello, I shared the post on [Slack](https://codeql-haby0.slack.com/files/T01QLKU2G8K/F01TX9Z8N9E)

**Comment by haby0** [comment]
@xcorail  Excuse me, do I need to close this issue?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Thanks for the submission @haby0! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query is not eligible for a reward under the Bug Bounty program for the following reason:
This query has a high rate of false positives and by nature we don't see how we could improve it.
Best regards and happy hacking!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
@xcorail Thanks for the reply, I am surprised by the audit results, but I respect the audit results.

**Comment by xcorail** [comment]
Hello @haby0 
Please be assured that each time that there is a disagreement with an author, the reviewer asks for other opinions in the Security Lab team, to confirm (or infirm) their position, and to ensure that the evaluation is fair. 
We appreciate your contributions to this program and are looking forward to get more! 

Best regards

**Comment by haby0** [comment]
Understand, haha, thanks again @xcorail
