### ISSUE TITLE
ihsinme: CPP add query for: CPP Add query for CWE-20 Improper Input Validation 

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#308]
## Report

the request detects situations when the check of the parameter participating in the positioning of the memory buffer occurs after the function call.
it is worth paying attention to the existence of two types of detection.
1.if the developer was mistaken and the parameter cannot be less than zero, in this case the request belongs to the correctness category
2.if the developer is not mistaken and the parameter can be less than zero, in this case it was used in a dangerous call before checking and this is security.
in my opinion, both situations require developer attention and fixes.

Relevant PR: https://github.com/github/codeql/pull/5326

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- https://github.com/irssi/irssi/pull/1270

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1128393 for bounty 284075 : [308] ihsinme: CPP add query for: CPP Add query for CWE-20 Improper Input Validation

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
thank
