### ISSUE TITLE
CodeQL query for finding ReDoS and Regex Injection vulnerabilities in Java

### ISSUE THREAD

**Issue by ggolawski** [github/securitylab#31]
## CVE ID(s)

There's no CVE for this.

## Report

I created 2 queries to detect ReDoS and Regex Injection vulnerabilities in Java.
The details including the list of covered cases (with examples) are present in PR: https://github.com/Semmle/ql/pull/2743

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
As per the PR review:
> These two queries are definitely something that we'll want to include in our default suite, and as you've probably noticed we already have ReDoS queries for C# and JavaScript (indeed it looks like you copy-pasted the regex-regexes from our C# query). There are a number of things I'd like to implement differently, so we can't merge this PR. However, there are certainly useful parts here, that I'm certain we'll be able to credit. I've made an issue for our follow-up #2804.

**Comment by xcorail** [comment]
Bounty payment order sent 🎉

**Comment by ggolawski** [comment]
Thank you!
