### ISSUE TITLE
[Java] CWE-918: Added URLClassLoader and WebClient SSRF sinks

### ISSUE THREAD

**Issue by p0wn4j** [github/securitylab#312]
## Query

Relevant PR: https://github.com/github/codeql/pull/5408

## CVE ID(s)

Not yet.

## Report

Server-side request forgery (also known as SSRF) is a web security vulnerability that allows an attacker to induce the server-side application to make HTTP requests to an arbitrary domain of the attacker's choosing.

In typical SSRF examples, the attacker might cause the server to make a connection back to itself, or to other web-based services within the organization's infrastructure, or to external third-party systems.

Class loaders are responsible for loading Java classes during runtime dynamically to the JVM. _URLClassLoader_ is used to load classes and resources from a search path of URLs referring to both JAR files and directories. If URLClassLoader's URL parameter can be controlled by an attacker, he can perform an SSRF/XSPA attack.

Spring WebFlux is a web framework that’s built on top of Project Reactor, to give you asynchronous I/O, and allow your application to perform better. _WebClient_ is a non-blocking, reactive client to perform HTTP requests. If WebClient instance is created by an attacker controlled URL, in this case attacker also can perform an SSRF attack. 

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1250305 for bounty 314829 : [312] [Java] CWE-918: Added URLClassLoader and WebClient SSRF sinks

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_
