### ISSUE TITLE
[Java] CWE-327: Query to detect insecure cipher suites and protocols in Tomcat server configuration

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#316]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5434

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

The Apache Tomcat server is the most widely used application server for deploying Java EE applications. Tomcat allows to configure cipher suites and TLS/SSL protocols in its configuration file <code>server.xml</code>. A cipher suite is a set of cryptographic algorithms used during SSL or TLS sessions to secure network connections between the client and the server. The set of algorithms that cipher suites usually include: a key exchange algorithm, a bulk encryption algorithm, and a Message Authentication Code (MAC) algorithm.
  
Old versions of TLS/SSL protocols such as <code>SSLv3</code> and <code>TLSv1</code>, and old versions of cipher suites with encryption ciphers such as <code>RC4</code> and <code>3DES</code>, and message authentication algorithms such as <code>SHA1</code> and <code>MD5</code> offer insufficient transport layer protection therefore are vulnerable to attacks.

The query detects insecure protocols and insecure ciphers configured in the Tomcat application server.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [Pet Store](https://github.com/antonakospanos/petstore)

**Comment by luchua-bc** [comment]
Please note to test this query, the <code>server.xml</code> file needs to be included in the CodeQL database. On my local DEV machine, I achieved this by setting the flag <code>--include-extension .xml</code> when executing the <code>codeql database</code> command.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by agustingianni** [comment]
Hello @luchua-bc we are reviewing your submission but it will take a little longer than expected due to the fact that server.xml is not added by default to LGTM, therefore we cannot properly assess the impact of your query yet.

**Comment by luchua-bc** [comment]
Thanks @agustingianni for the update.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by agustingianni** [comment]
Hello @luchua-bc,

unfortunately after some input from my team mates, we concluded that the query targets a configuration file that is part of tomcat's configuration (deployment) and it is not usually part of a codebase. I've done some searches on GitHub and grep.app and it did not give me enough results to think otherwise.

We are therefore, rejecting this submission.

Thank you for your submission.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @agustingianni for reviewing this PR.

Although not all Java EE projects put their Tomcat server configuration in the codebase, the [search of Tomcat server.xml](https://github.com/search?q=Catalina+language%3Axml+filename%3Aserver.xml&type=Code) returns about 43,865 results in public repositories of GitHub. And the [search on explicit Tomcat cipher configuration](https://github.com/search?q=ciphers+language%3Axml+filename%3Aserver.xml&type=Code) returns over 800 matched results e.g. the one I referenced.

And the default Tomcat configuration isn't restrictive enough therefore less strong protocols and cipher suites are allowed, which is a very common issue with Java EE deployment. Since cipher suites and TLS/SSL protocols are only configured in Tomcat server.xml, the precision of this query is high. Without tuning the server configuration, compliance check e.g. with the popular [SSL Labs tool](https://www.ssllabs.com/ssltest/) will fail. So it's a common item on the security checklist of application deployment therefore I have thought this is an interesting category of query.

I'm a little surprised that the submission is rejected because Tomcat's configuration (deployment) is not usually part of a codebase but I respect the decision made.
