### ISSUE TITLE
[Python] CWE-400: Regular Expression Injection

### ISSUE THREAD

**Issue by jorgectf** [github/securitylab#318]
## Query

Relevant PR: https://github.com/github/codeql/pull/5442

## Report

Constructing regular expressions directly from tainted data enables attackers to craft regular expressions in order to cause a Denial of Service or change the behaviour of the application depending on the matched string.

This query identifies cases in which a regular expression is used without being escaped before by `re.escape` (see [python re documentation](https://docs.python.org/3/library/re.html)).

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- PRs providing fix:
- - https://github.com/cve-search/cve-search/pull/629
- - https://github.com/kevoreilly/CAPEv2/pull/473
- - https://github.com/cuckoosandbox/cuckoo/pull/3188
- - https://github.com/tubone24/ebook_homebrew/pull/289
- - https://github.com/ctxis/CAPE/pull/480

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by jorgectf** [comment]
Polished a bit the description after the detail change related to Regular Expression __Injection__.

**Comment by agustingianni** [comment]
Hello Jorge, the security lab is evaluating your submission, we will ping you back soon. Thanks for the submission

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1196124 for bounty 303883 : [318] [Python] CWE-400: Regular Expression Injection

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
