### ISSUE TITLE
[Python] CWE-522: Insecure LDAP Authentication

### ISSUE THREAD

**Issue by jorgectf** [github/securitylab#321]
## Query

Relevant PR: https://github.com/github/codeql/pull/5445

## Report

This query identifies cases in which a LDAP connection doesn't use a secure (TLS) channel.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [debnet/common-framework](https://github.com/debnet/common-framework)

**Comment by jorgectf** [comment]
The provided result does not actually get flagged by the query, since it is taking the value from a custom setting that hasn't been established ([here](https://github.com/debnet/common-framework/blob/master/common/settings.py)) (The query itself works since quick eval'ing the sink works). How should this kind of situations when the parameter *may* be a remote server be undertaken? Anyway I'm currently querying some projects regarding this issue and another flagged project will arise soon.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by kevinbackhouse** [comment]
@jorgectf: I'm sorry, I didn't understand your previous comment. Is/was there a vulnerability in debnet/common-framework that this query would find? If so, please could you provide a link to the corresponding fix commit?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Generate Query Results**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by jorgectf** [comment]
> @jorgectf: I'm sorry, I didn't understand your previous comment. Is/was there a vulnerability in debnet/common-framework that this query would find? If so, please could you provide a link to the corresponding fix commit?

Hi Kevin, thanks for your reply.

The project doesn't get flagged by default as the LDAP host is defined [here](https://github.com/debnet/common-framework/blob/f4a0b424141691b296e25167759e5a95c84bcc29/common/settings.py#L30) and so I haven't reported the finding. 

A secure connection would use `ldaps://` or call `start_tls()`. Since there's no call to `start_tls()`, this project can be used to test the sink of the query, as most of the projects out there use a custom setting (like the mentioned repo) to set the LDAP host. That's the main point of my previous comment; should this query flag [_empty_](https://github.com/debnet/common-framework/blob/f4a0b424141691b296e25167759e5a95c84bcc29/common/settings.py#L30) LDAP hosts __without__ a `start_tls()` (or alike) call? Feel free to post a comment on the query PR.

However, [as mentioned in the PR](https://github.com/github/codeql/pull/5445#issuecomment-863376323), I've rewritten [the previous LDAP modeling](https://github.com/jorgectf/codeql/blob/f807c2f52b9ce04ba63831d5dbe8cbdb9cc54dae/python/ql/src/experimental/semmle/python/frameworks/LDAP.qll) in https://github.com/github/codeql/pull/5444, so I'd like to wait until the last PR gets reviewed, merged and will port this query to `ApiGraphs` and make it cover `ldap2` as well. 

Could we put this submission on hold until https://github.com/github/codeql/pull/5444 gets merged and github/codeql#5445 rewritten?

Thanks for your time.

**Comment by kevinbackhouse** [comment]
@jorgectf: No problem. Just @ me when you have made more progress and I'll take another look.

**Comment by jorgectf** [comment]
Thanks @kevinbackhouse!

**Comment by jorgectf** [comment]
https://github.com/github/codeql/pull/5445#issuecomment-885058566 @kevinbackhouse I've just rewritten the query :)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1350076 for bounty 337293 : [321] [Python] CWE-522: Insecure LDAP Authentication

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by jorgectf** [comment]
Thank you @kevinbackhouse @xcorail 🙏
