### ISSUE TITLE
[Java] CWE-555: Query to detect plaintext credentials in Java properties files

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#327]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5538

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

It's a very common issue that credentials are stored in plaintext in application’s properties files. Common credentials include but are not limited to LDAP, mail, database, proxy account, and so on. 

Credentials management issues occur with such a configuration. Storing plaintext credentials in a properties file allows anyone who can read the file access to the protected resource. Good credentials management guidelines require that credentials never be stored in plaintext.

This query detects plaintext credentials stored in Java properties files by checking common patterns of confidential credentials used in Java applications.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [sscpac/swif](https://github.com/sscpac/swif)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Hello @luchua-bc,

Unfortunately the CodeQL and SecLab teams consider that this query does not qualify for a bounty since it does not meet the minimum complexity requirements regardless of using a dataflow configuration.

We are therefore, rejecting this submission.

Thank you for your submission.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
