### ISSUE TITLE
Security Lab RSS issue

### ISSUE THREAD

**Issue by elreydetoda** [github/securitylab#328]
Since there were no blank templates [allowed](https://github.com/github/securitylab/blob/main/.github/ISSUE_TEMPLATE/config.yml#L1), I wasn't able to classify this as something else. So, sorry for the wrong type of issue submission but I had no choice. Feel free to close the issue, but I just wanted to let you know since I enjoy reading all the different posts/notifications you put out under the [GitHub Security Lab Research](https://securitylab.github.com/research/).

So, I don't know where you publish that with the Jekyll configuration that you use, but I recently was checking my RSS feeds and noticed that your rss feed stopped working. I guess that maybe the website was re-done, and it stopped working. This was the old rss feed url: <https://securitylab.github.com/research/feed>

The new feed url doesn't have anything populated in it, and I would imagine it would be all of your content on that website and not just the security posts now. Just wanted to drop a quick note so you all were aware.

**Comment by xcorail** [comment]
Thanks for pointing this out to us. I have created an issue in our proper internal repo. Thanks

**Comment by elreydetoda** [comment]
Awesome, thank you @xcorail 😁

**Comment by xcorail** [comment]
This should be fixed now @elreydetoda

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by elreydetoda** [comment]
> This should be fixed now @elreydetoda

Yep, everything looks good. Thank @xcorail :grin:
