### ISSUE TITLE
[JAVA]: CWE-347 - Improper Verification of Cryptographic Signature : Potential for Auth Bypass

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/securitylab#333]
## Query

Relevant PR: https://github.com/github/codeql/pull/5597

## CVE ID(s)

https://i.blackhat.com/USA-19/Thursday/us-19-Jaiswal-Preventing-Authentication-Bypass-A-Tale-Of-Two-Researchers.pdf
https://www.zofrex.com/blog/2020/10/20/alg-none-jwt-nhs-contact-tracing-app/
https://github.com/DP-3T/dp3t-sdk-backend/security/advisories/GHSA-5m5q-3qw2-3xf3
### Found using this query:
https://github.com/grassrootza/grassroot-platform/security/advisories/GHSA-f65w-6xw8-6734
https://github.com/ManyDesigns/Portofino/security/advisories/GHSA-6g3c-2mh5-7q6x

## Report

A JWT consists of three parts: header, payload, and signature.
The `io.jsonwebtoken.jjwt` library is one of many libraries used for working with JWTs.
It offers different methods for parsing tokens like `parse`, `parseClaimsJws`, and `parsePlaintextJws`.
The last two correctly verify that the JWT is properly signed.
This is done by computing the signature of the combination of header and payload and
comparing the locally computed signature with the signature part of the JWT.

Therefore it is necessary to provide the `JwtParser` with a key that is used for signature validation.
Unfortunately the `parse` method **accepts** a JWT whose signature is empty although a signing key has been set for the parser.
**This means that an attacker can create arbitrary JWTs that will be accepted.**

This is a *high* impact query as being able to forge token often leads to an *auth bypass*.
See also the links at the top.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

https://github.com/apache/pulsar/pull/9172

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by intrigus-lgtm** [comment]
I added two results to the above post that were found using this query:
https://github.com/grassrootza/grassroot-platform/security/advisories/GHSA-f65w-6xw8-6734
https://github.com/ManyDesigns/Portofino/security/advisories/GHSA-6g3c-2mh5-7q6x

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by intrigus-lgtm** [comment]
Thank you :tada:

**Comment by xcorail** [comment]
Created Hackerone report 1184041 for bounty 300317 : [333] [JAVA]: CWE-347 - Improper Verification of Cryptographic Signature : Potential for Auth Bypass

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by intrigus-lgtm** [comment]
I've written a blog post for this query:
https://intrigus.org/research/2021/08/05/finding-insecure-jwt-signature-validation-with-codeql/
