### ISSUE TITLE
[C#]: HttpOnly and Secure Cookies for .NET Core and .NET

### ISSUE THREAD

**Issue by edvraa** [github/securitylab#338]
## Query

https://github.com/github/codeql/pull/5579

## Report

There was rudimentary Secure Cookie support for .NET. I have reworked it and added HttpOnly for .NET and Secure and HttpOnly for .NET Core.

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1301752 for bounty 326146 : [338] [C#]: HttpOnly and Secure Cookies for .NET Core and .NET
