### ISSUE TITLE
ihsinme: CPP Add query for CWE-783 Operator Precedence Logic Error When Use Bool Type

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#340]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5325

## Report
The query finds the places of erroneous use of logical operations. For example, unary minus does not work in front of a boolean type, and increment always evaluates to true. Or lack of precedence in an assignment and comparison expression. all of these situations can lead to an error in the program.
*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

https://wiki.sei.cmu.edu/confluence/display/c/EXP00-C.+Use+parentheses+for+precedence+of+operation
Relevant PR: github/codeql#5325

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- SerenityOS/serenity#4494
- mysql/mysql-server#331

**Comment by ihsinme** [comment]
this request of mine has been in a null state for a long time.
I'm worried why it doesn't go into the `CodeQL Initial assessment state`.
maybe I did something wrong?

**Comment by JarLob** [comment]
Hi @ihsinme, this is a glitch in sync program. However your submission is in the first state for a while even if there is no bot notification. We'll keep an eye on it.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
Good day.
I'm sorry.
but it seems to me that there is something wrong with this request.
it has been in one state for about a month.
Is there anything I can do to change this?
Thank you.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1241578 for bounty 313174 : [340] ihsinme: CPP Add query for CWE-783 Operator Precedence Logic Error When Use Bool Type

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
thanks
