### ISSUE TITLE
ihsinme: CPP Add query for CWE-691 Insufficient Control Flow Management When Using Bit Operations

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#343]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5600

## Report
the request detects misuse of bitwise operations. I tried to exclude false positives as much as possible. at the same time, the main mistakes contain a situation of incorrect operation with a function call. For example, when the developer forgot that the bit operation does not exclude the call of all elements of the expression and organized the verification of the call arguments. this will cause the function to be called regardless of the results of the parameter evaluation.
https://cwe.mitre.org/data/definitions/691.html

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- facebook/zstd#2541

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1175839 for bounty 297927 : [343] ihsinme: CPP Add query for CWE-691 Insufficient Control Flow Management When Using Bit Operations

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
thanks
