### ISSUE TITLE
ihsinme: CPP Add query for CWE-691 Insufficient Control Flow Management After Refactoring The Code

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#347]
## Query

Relevant PR: https://github.com/github/codeql/pull/5601

## Report

Good day.
This PR looks for situations of losses after refactoring. Two situations are considered. The first forgotten empty while after the loop. And arephmetics in comparison.
the first case is quite rare.
and can lead to an impact on the availability of resources. (hang)
but the second is widely represented.
and is more often influenced by the logic of the program
I tried to remove the false detection as much as possible.
https://cwe.mitre.org/data/definitions/691.html

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

axboe/fio#1194

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
thanks

**Comment by xcorail** [comment]
Created Hackerone report 1184040 for bounty 300316 : [347] ihsinme: CPP Add query for CWE-691 Insufficient Control Flow Management After Refactoring The Code

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
