### ISSUE TITLE
Golang: Add query to detect CSRF vulnerabilities

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#353]
## Query

Relevant PR: https://github.com/github/codeql-go/pull/532

## Description
When a web server is designed to receive a request from a client without any mechanism for verifying that it was intentionally sent, then it might be possible for an attacker to trick a client into making an unintentional request to the web server which will be treated as an authentic request. This can be done via a URL, image load, XMLHttpRequest, etc. and can result in exposure of 
data or unintended code execution.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by m-y-mo** [comment]
@porcupineyhairs We've reviewed the results running on lgtm, unfortunately, there is no result for this query. Would you be able to provide a TP for this query in a real world repo to meet the submission criteria? Thanks.

**Comment by porcupineyhairs** [comment]
@m-y-mo I have found a CVE. However, it is not detected by the query in its current form. I will make the changes and get back soon.

**Comment by m-y-mo** [comment]
@porcupineyhairs As we have not hear back from you for more than 3 months, I'm closing this issue. Please feel free to reopen the issue when you found a CVE. Please note that the issue will be evaluated according to the situation and rules when it is reopened. Thanks.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_
