### ISSUE TITLE
[Java] CWE-094: Rhino code injection

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#356]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5802

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Rhino is a JavaScript engine written fully in Java and managed by the Mozilla Foundation.
It serves as an embedded scripting engine inside Java applications which allows
Java-to-JavaScript interoperability and provides a seamless integration between the two
languages. If an expression is built using attacker-controlled data, and then evaluated in
a powerful context, it may allow the attacker to run arbitrary code.

Typically an expression is evaluated in the powerful context initialized with
initStandardObjects that allows an expression of arbitrary Java code to
execute in the JVM, which is dangerous and poses security risks.

The query detects unsafe usage of Rhino expressions. 

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [Rhino Website](https://github.com/jojozhuang/tutorial-projects/tree/master/RhinoWebsite)

**Comment by pwntester** [comment]
Wondering where did you get the idea from :smile:

Anyhow, I think this query makes more sense as a new sink for the [Nashorn](https://github.com/github/codeql/blob/main/java/ql/src/experimental/Security/CWE/CWE-094/ScriptEngine.ql) one. Maybe change the name of that query to make it more generic (eg: Script Injection)

**Comment by luchua-bc** [comment]
Hi @pwntester,

As code injection is a hot topic among CodeQL query researchers and quite a few queries in this area were accepted by the security lab recently, I iterated popular frameworks/implementations and it's a fairly straight-forward decision to write one for the Rhino JavaScript Engine.

I've made the requested change by merging those two queries into one since they are both related to JavaScript engines.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
> As code injection is a hot topic among CodeQL query researchers and quite a few queries in this area were accepted by the security lab recently, I iterated popular frameworks/implementations and it's a fairly straight-forward decision to write one for the Rhino JavaScript Engine.

I was referring to our [second episode of LiveQL](https://www.youtube.com/watch?v=wPqK-Ealz-0)

**Comment by luchua-bc** [comment]
> > As code injection is a hot topic among CodeQL query researchers and quite a few queries in this area were accepted by the security lab recently, I iterated popular frameworks/implementations and it's a fairly straight-forward decision to write one for the Rhino JavaScript Engine.
> 
> I was referring to our [second episode of LiveQL](https://www.youtube.com/watch?v=wPqK-Ealz-0) 😄

That's a nice video. I should have watched before.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1204660 for bounty 306371 : [356] [Java] CWE-094: Rhino code injection

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Thanks @xcorail for the quick turn-around and the bounty.
