### ISSUE TITLE
XPath Injection query in java

### ISSUE THREAD

**Issue by SpaceWhite** [github/securitylab#36]
## CVE ID(s)

No CVE

## Report
XPath injection is available in c# and javascript query but it is not available in java query. Created a xpath injection query in java https://github.com/Semmle/ql/pull/2800
- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Hey @SpaceWhite 👋 
Can you please send your email at securitylab@github.com? 
Thanks

**Comment by xcorail** [comment]
Payment order sent
`Created Hackerone report 824925 for bounty 206494 : [36] XPath Injection query in java`

**Comment by JLLeitschuh** [comment]
🎉 https://hackerone.com/reports/824925

Very cool!

**Comment by abd525** [comment]
nice
