### ISSUE TITLE
C++: Support Pqxx connector to search for sql injections to Postgres

### ISSUE THREAD

**Issue by japroc** [github/securitylab#361]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5842

## CVE ID(s)

* No CVEs

## Report

The main goal of my PR it to add support of pqxx connector.
Right now there are only MyQSL and SQlite support. And it is based solely on function name.
Pqxx sink is a bit more complex, because functions like "exec" may lead to high false positive rate.

I basically reused existing SqlTainted query, and created a custom SqlPqxxTainted query. I think that pqxx support should be implemented in Security.qll, but i seems not so simple to overwrite the logic behind SqlTainted query and it's Taint Configuration. That is why i decides to create separate query. I have also added example file SqlPqxxTainted.c and SqlPqxxTainted.qhelp which almost completely repeats SqlTainted.qhelp.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

Probably i would tell about my experience on upcoming conference on defense track about SAST.

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- I dont have useful findings with this query.
- [For example this injection on contributors list which comes from config file. Not sure it's an issue](https://github.com/CanalTP/navitia/blob/dev/source/kraken/fill_disruption_from_database.cpp#L172).
- [Also i have send a PR to fix potential sqli with originates from reading fs path. But this one does not look risky too](https://github.com/dns-stats/hedgehog/pull/190)
- I think it's because currently CodeQL in unable to find more complex source types than described in Security.qll. But i am in process. It's not simple and fast, because vast majority of C++ projects are not easy to compile. As i said the main goal it to add support for pqxx connector. It actually successfully find that type of sink in open source projects i have tested. Also it helped me to find issues on my work by using `predicate isSource(DataFlow::Node source) { any() }` as Source and wide isAdditionalTaintStep:
```
  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    exists(FunctionCall fc |
      fc.getAnArgument() = pred.asExpr() and
      fc.(Expr) = succ.asExpr()
    )
  }
```

**Comment by japroc** [comment]
By the way, i did not use TaintConfiguration from original SqlTainted query, because i was unable to overwrite `isSanitizer` in a private class. And actually i dont understand the difference between these 2 TaintTracking analysis: https://github.com/github/codeql/tree/main/cpp/ql/src/semmle/code/cpp/dataflow and https://github.com/github/codeql/tree/main/cpp/ql/src/semmle/code/cpp/ir/dataflow?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by antonio-morales** [comment]
Hi @japroc!

You need to provide a finding in order to meet the submission criteria.

Can you provide a result for this query?

**Comment by japroc** [comment]
Hi, @antonio-morales!

As i understand, you are talking about real projects findings, and not example attached to a query in the same folder?

Finding bugs in cpp projects is not trivial. The first reason it is not easy to compile every project i want to test. The second - taint tracking does not work perfectly, especially with classes.

I need time to find good findings. Maybe you can give some advices on that taks?

**Comment by anticomputer** [comment]
@japroc you can test against a previously uncovered/fixed/known bug that's already been fixed, the goal here is to show that your pattern exists in shipped code and that your query finds this pattern as such, but we do not expect you to post new or undisclosed vulnerabilities in this context.

**Comment by japroc** [comment]
Hi, @anticomputer and @antonio-morales! 

Here is a straightforward example for project https://github.com/arman-novikov/PSQLcomet. Flow:
1) https://github.com/arman-novikov/PSQLcomet/blob/master/ws_server.cpp#L140 - recv to rBuffer
2) https://github.com/arman-novikov/PSQLcomet/blob/master/ws_server.cpp#L152
3) https://github.com/arman-novikov/PSQLcomet/blob/master/ws_server.cpp#L153
4) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_comet.cpp#L20
5) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_comet.cpp#L35
6) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/ws_server_utils.cpp#L80
7) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/ws_server_utils.cpp#L119
8) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/ws_server_utils.cpp#L124
9) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_comet.cpp#L36
10) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_manager.cpp#L62
11) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_manager.cpp#L69
12) https://github.com/arman-novikov/PSQLcomet/blob/a77b9d970dbd58500a65d5d187ab5dad7872a985/psql_manager.cpp#L76

But CodeQL fails to taint that simple flow. I dont know why, but it has to find that vulnerability.

**Comment by JarLob** [comment]
@MathiasVP, I see the query is already merged. Do you have ideas why it doesn't flag the case above? Any additional query or model in C++ ql that could be improved?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by MathiasVP** [comment]
> @MathiasVP, I see the query is already merged. Do you have ideas why it doesn't flag the case above? Any additional step or model in C++ ql that could be improved?

Hmmm... I _do_ see a problem, yes. I think there's a problem with extraction, and so we might be failing some analyses because we can't see all of the code. I'll continue investigating!

**Comment by MathiasVP** [comment]
Update: We have identified the extraction issue. It's a known problem, and we've bumped up the priority on the issue.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1241583 for bounty 313179 : [361] C++: Support Pqxx connector to search for sql injections to Postgres

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by japroc** [comment]
Thank you!
