### ISSUE TITLE
[Java] CWE-798: Query to detect hard-coded Azure credentials

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#362]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5852

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Microsoft Azure is one of the most popular cloud computing solutions for building, testing, deploying, and managing applications and services in the cloud.

Azure offers a well-maintained [Java SDK](https://github.com/Azure/azure-sdk-for-java) for provisioning, managing, and using Azure resources from Java application code. The Azure SDK for Java is composed of many individual Java libraries that relate to specific Azure services.

The query detects calling Azure SDK with a hard-coded user name and password or client secret. 

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [kartikchhapia/msftChangeNotifications](https://github.com/kartikchhapia/msftChangeNotifications)
- [jpnaidu07/azure-key-vault-examle](https://github.com/jpnaidu07/azure-key-vault-examle)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Hey @luchua-bc 

Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query is not eligible for a reward under the Bug Bounty program for the following reasons:
- It doesn't meet the minimum complexity requirements: 
> To be eligible for a bounty, queries must be non-trivial, and meet a minimum complexity requirement. More concretely, queries that simply look for one or two AST elements, or that could be easily implemented with a linter or simple grep, may not be considered interesting enough for a bounty. Queries must also be sufficiently general to cover a class of vulnerabilities and may not be tailored to a specific CVE.

Looking forward to your future submissions!
Best regards and happy hacking!

**Comment by luchua-bc** [comment]
Hi @pwntester,

Thanks for reviewing this PR. Sorry I don't get why the query doesn't meet the minimum complexity requirements so I would like more explanation.

Although its main part is three lines' addition to the library <code>SensitiveApi.qll</code>, it does take advantage of the shared dataflow configuration <code>HardcodedCredentialApiCallConfiguration</code> in <code>HardcodedCredentialsApiCall.ql</code>, which look for more than two AST elements and cannot be implemented with a linter or simple grep. For example, with its <code>isBarrier</code> predicate, credentials loaded as environment variables are not treated as hard-coded credentials to avoid false positives. I didn't re-invent the wheel to re-create the complex query because we already have the flow configuration in the CodeQL repository.

If this submission is invalid, does it mean other sensitive APIs in <code>SensitiveApi.qll</code> don't meet the minimum complexity requirements either? The query <code>HardcodedCredentialsApiCall.ql</code> and its dependent queries were contributed by quite a few researchers including @aschackmull, @p0, and @Marcono1234, and are pretty comprehensive. Also the other query [Java: CWE-798 - Hardcoded AWS credentials](https://github.com/github/securitylab/issues/129) written by me, which has a similar structure but handles hard-coded AWS credentials, was triaged as a valid submission just nine months ago.

I submitted this query because I think it fits in the category of "improve an existing query and extend its coverage to detect additional vulnerabilities" in the [Github policy](https://hackerone.com/github-security-lab?type=team) for detecting additional vulnerabilities of hard-coded credentials with Azure SDK.

Please correct me if my understanding is wrong. Thanks.

**Comment by pwntester** [comment]
Hi @luchua-bc,

Even if query improvements are indeed part of the program, they are also subject to the same rules as any original submission, including the minimum complexity rule detailed in the Out Of Scope section in https://hackerone.com/github-security-lab?type=team. We will clarify that in the FAQ of the bounty program.

As per the mentioned contributions, all of them were contributed outside of the bounty program, which is consistent with our decision.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Hi @pwntester,

The contribution I mentioned above, which is [Java: CWE-798 - Hardcoded AWS credentials](https://github.com/github/securitylab/issues/129) for hard-coded AWS credentials, was contributed within the bounty program. I'm not aware of scope change in the last 9 months so it's confusing.

**Comment by pwntester** [comment]
This issue was triaged and discussed by our triage team and it was decided that the evaluation and scoring at that time were erroneous. We are sorry for the confusion and inconveniences it may have caused you.
