### ISSUE TITLE
ihsinme: CPP Add query for CWE-1126: Declaration of Variable with Unnecessarily Wide Scope

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#364]
## Query

Relevant PR: https://github.com/github/codeql/pull/5767

## Report

the query finds the places where the variable is declared in the body of the loop. in situations where a similar variable is already used in a condition. my analysis showed that such coding methods are often used in various projects. however, these places do not always affect safety, the simplest example is the `for` loop.
therefore, I have as much as possible limited the request to identify situations that have a real impact on safety.

https://wiki.sei.cmu.edu/confluence/display/c/DCL01-C.+Do+not+reuse+variable+names+in+subscopes

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

sleuthkit/sleuthkit#2329
https://github.com/RediSearch/RediSearch/blob/efe031ea498ca4299064027641fad3b8f262ef6a/src/rmutil/util.c#L66

**Comment by ihsinme** [comment]
another useful discovery.
excluding the perpetual cycle.

https://github.com/ryuichiueda/glueutils/pull/2

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by antonio-morales** [comment]
Hi @ihsinme!

We've reviewed the results running on LGTM, but unfortunately, there is no result for this query. Would you be able to provide a TP for this query in real-world software to meet the submission criteria? 

Thanks.

**Comment by ihsinme** [comment]
good day.
above in the request, I presented two fixes that seemed to me TP.
ryuichiueda/glueutils#2
sleuthkit/sleuthkit#2329

if for further consideration it is necessary more, I will certainly look more.

**Comment by ihsinme** [comment]
> (glueutils is an experimental repo with only 3 stars)

I totally agree. it looks like some kind of internal project, at the initial stage. but I brought this direction because `ryuichiueda` itself seemed to me quite professional.

**Comment by anticomputer** [comment]
@ihsinme thanks for the update, we'll move this forward for further review

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1219494 for bounty 309997 : [364] ihsinme: CPP Add query for CWE-1126: Declaration of Variable with Unnecessarily Wide Scope

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
Thanks
