### ISSUE TITLE
[Java]: CWE-502 Add UnsafeDeserialization sinks

### ISSUE THREAD

**Issue by haby0** [github/securitylab#367]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5881

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
Java's unsafe deserialization sink will continue to submit pr later.this is one of them. https://github.com/github/codeql/pull/5971

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1241575 for bounty 313171 : [367] [Java]: CWE-502 Add UnsafeDeserialization sinks

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
@xcorail thank you.  For this PR, I want to apply for an increase in bounty awards.  Because it can detect more deserialization vulnerabilities, including personal research results.  In addition, I also added more sinks to other PRs (no bounty application).

**Comment by xcorail** [comment]
Hello @haby0 

> Because it can detect more deserialization vulnerabilities

The scoring of our program depends on various factors, not only how many vulns it can detect. See the [FAQ](https://securitylab.github.com/bounties/) about how we determine the rewards.

> I also added more sinks to other PRs (no bounty application).

This is much appreciated, but this is not uncommon, as for other open source projects. Community members regularly propose query improvements or entire new queries without submitting through the bounty program.

**Comment by haby0** [comment]
> Hello @haby0
> 
> > Because it can detect more deserialization vulnerabilities
> 
> The scoring of our program depends on various factors, not only how many vulns it can detect. See the [FAQ](https://securitylab.github.com/bounties/) about how we determine the rewards.
> 
> > I also added more sinks to other PRs (no bounty application).
> 
> This is much appreciated, but this is not uncommon, as for other open source projects. Community members regularly propose query improvements or entire new queries without submitting through the bounty program.

I have read carefully about how to determine the bounty amount.  In this pr deserialization vulnerability detection, some can be found in general software, such as: hessian, castor, etc.  So I think it is high risk to evaluate from the severity of the vulnerability and the number of users.

**Comment by xcorail** [comment]
As I said, and as written in the FAQ, other factors such as the quality of the code and documentation of the CodeQL query are also taken into account in the determination of the bounty award. 
I will ask in the team for other opinions and let you know.

**Comment by haby0** [comment]
> As I said, and as written in the FAQ, other factors such as the quality of the code and documentation of the CodeQL query are also taken into account in the determination of the bounty award.
> I will ask in the team for other opinions and let you know.

thanks for the reply.

**Comment by pwntester** [comment]
Hi @haby0, just reviewed the seclab score for this submission.

> So I think it is high risk to evaluate from the severity of the vulnerability and the number of users.

We agree with the severity (impact) assessment and we scored your submission accordingly in the highest range. However, we didn't find any data backing your second statement (number or users). A query run on 26K projects on LGTM returned a very low number of hits (12) and most of them were on 0-star projects (student or test projects). These libraries you added support for were featured in the popular Marshalsec research but the adoption of these libraries in OSS software is very low.

I hope this helps clarify the discrepancies. We encourage you to keep up with the great work!

**Comment by haby0** [comment]
> Hi @haby0, just reviewed the seclab score for this submission.
> 
> > So I think it is high risk to evaluate from the severity of the vulnerability and the number of users.
> 
> We agree with the severity (impact) assessment and we scored your submission accordingly in the highest range. However, we didn't find any data backing your second statement (number or users). A query run on 26K projects on LGTM returned a very low number of hits (12) and most of them were on 0-star projects (student or test projects). These libraries you added support for were featured in the popular Marshalsec research but the adoption of these libraries in OSS software is very low.
> 
> I hope this helps clarify the discrepancies. We encourage you to keep up with the great work!

Thank you for your reply. I understand what you mean. One embarrassing point is that some general open source software requires customized rules. Reference article: [Castor and Hessian java deserialization vulnerabilities](https://securitylab.github.com/research/hessian-java-deserialization-castor-vulnerabilities/)

**Comment by pwntester** [comment]
> Thank you for your reply. I understand what you mean. One embarrassing point is that some general open source software requires customized rules. Reference article: Castor and Hessian java deserialization vulnerabilities

Thanks for understanding, we are aware that rating the scope of the query by running it on LGTM is not perfect and may have both FPs and FNs that are not caused by the query being evaluated. However, it gives a good enough estimation of the scope in an objective way, which is much better and *fair* than subjectively rating it.

**Comment by haby0** [comment]
Long live fairness. Thank you for your review and answer. @pwntester @xcorail @smowton .
