### ISSUE TITLE
[Java] JShell Injection

### ISSUE THREAD

**Issue by haby0** [github/securitylab#374]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/5955

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

The Java Shell tool (JShell) is an interactive tool for learning the Java programming language and prototyping Java code. JShell is a Read-Evaluate-Print Loop (REPL), which evaluates declarations, statements, and expressions as they are entered and immediately shows the results. If an expression is built using attacker-controlled data and then evaluated, it may allow the attacker to run arbitrary code.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

[deepjavalibrary/djl-demo](https://github.com/deepjavalibrary/djl-demo): [source](https://github.com/deepjavalibrary/djl-demo/blob/a944e5a0a6739bebc050dbbc96f589f54fe7500d/web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/BlockRunnerController.java#L40) -> [sink](https://github.com/deepjavalibrary/djl-demo/blob/master/web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/InteractiveShell.java#L68)

**Comment by haby0** [comment]
> Can you provide one result that is found by your query?

https://grep.app/search?q=jdk.jshell.JShell

**Comment by haby0** [comment]
> Can you provide one result that is found by your query?

You are securitylab team do?

**Comment by intrigus-lgtm** [comment]
> > Can you provide one result that is found by your query?
> 
> You are securitylab team do?

No, I'm not affiliated with the securitylab.

**Comment by haby0** [comment]
> > > Can you provide one result that is found by your query?
> > 
> > 
> > You are securitylab team do?
> 
> No, I'm not affiliated with the securitylab.

Oh oh, I thought you were from securitylab.
You can take a look at this [repository](https://github.com/deepjavalibrary/djl-demo). 
[source](https://github.com/deepjavalibrary/djl-demo/blob/a944e5a0a6739bebc050dbbc96f589f54fe7500d/web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/BlockRunnerController.java#L40) -> [sink](https://github.com/deepjavalibrary/djl-demo/blob/master/web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/InteractiveShell.java#L68)

**Comment by antonio-morales** [comment]
Hi  @haby0 !!

I need a more detailed description of this vulnerability in order to meet the submission criteria

**Comment by haby0** [comment]
> Hi @haby0 !!
> 
> I need a more detailed description of this vulnerability in order to meet the submission criteria

@antonio-morales Please review again, thank you!!

**Comment by anticomputer** [comment]
@haby0 hello, I am currently on call for bounty review, thank you for updating the description. I am evaluating relevant scope, were you able to determine use of JShell in any contexts beyond the provided demo example?

**Comment by haby0** [comment]
Thanks for the review, you can take a look at these two:

https://github.com/SpencerPark/IJava/blob/a03ad7712a5e8c893bbffc527efd66ae9aae0207/src/main/java/io/github/spencerpark/ijava/execution/CodeEvaluator.java#L76

https://github.com/runelite/runelite/blob/master/runelite-jshell/src/main/java/net/runelite/jshell/ShellPanel.java#L314

**Comment by anticomputer** [comment]
Thank you for providing additional examples @haby0, I'll move this forward in the evaluation process accordingly.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by haby0** [comment]
> Thank you for providing additional examples @haby0, I'll move this forward in the evaluation process accordingly.

Thank you.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1250307 for bounty 314831 : [374] [Java] JShell Injection
