### ISSUE TITLE
ihsinme:CPP Add query for CWE-415 Double Free

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#375]
## Query

Relevant PR:  https://github.com/github/codeql/pull/5766

## Report

In this request, I consider the situation of double freeing of allocated memory.
this mistake is quite common. and can affect security in different ways.

https://wiki.sei.cmu.edu/confluence/display/c/MEM30-C.+Do+not+access+freed+memory

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- samtools/htslib#1274

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1219491 for bounty 309994 : [375] ihsinme:CPP Add query for CWE-415 Double Free

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
Thanks
