### ISSUE TITLE
[Java] CWE-326: Query to detect weak HMAC secret keys used to sign JWT

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#380]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/6021

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

JSON Web Token (JWT) is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. This information can be verified and trusted through a digital signature. JWTs can be signed using a secret (with the HMAC algorithm) or a public/private key pair using RSA or ECDSA.

JWT Best Practices require human-memorizable passwords MUST NOT be directly used as the key to a keyed-MAC algorithm such as “HS256”. RFC 7518 recommends to use a password that is as large as (or larger than) the derived key length in JSON web algorithms. Common JWT signature algorithms are HS256, HS384, and HS512.

Popular JWT libraries offer a method to set signing key with a handy string argument in addition to the method with a byte array argument taking the binary cryptographic key. It is a common mistake that JWT users are confused by the method signature and attempted to use raw password strings as the key argument, which is almost always incorrect for cryptographic hashes and can produce insecure results.

Signature algorithms are vulnerable to brute force attack when a weak key of shorter length is used. This query detect uses of signature algorithms with a weak key of shorter length in two popular JWT frameworks jjwt and jose4j:

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [sports-mall-server](https://github.com/itning/sports-mall-server)
- [TLOG16RS](https://github.com/kovacskornel/TLOG16RS)

**Comment by JarLob** [comment]
Hi @luchua-bc,
Thanks for the submission! We have reviewed your report and validated your query. After an internal assessment we have determined this query is not eligible for a reward under the Bug Bounty program.
Even if the secret is complex and long, it is **hardcoded**. This pattern should be covered by a new sink in hardcoded credentials query (if not covered already). If the secret is properly loaded from a production configuration file or environment the length cannot be evaluated statically.
Please note, that this case is different from https://github.com/github/codeql/pull/4926 where encryption strength is determined by a separate API independent from the secret itself.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
Hi @JarLob, @pwntester, and @owen-mc,

As the submission of hard-coded secrets for signing JWT tokens was accepted for Golang (#557), I'm wondering whether this submission shall be accepted as well. Please advise on whether I shall make some changes, broaden its scope, resubmit as a new issue, or please clarify the difference.

Thanks,
@luchua-bc

**Comment by JarLob** [comment]
Hi @luchua-bc, please note, that by closing the submission we suggested you should detect any hardcoded JWT secret because this is the primary issue, not the fact that the hardcoded key is shorter than some arbitrary length. We have a general query for hardcoded secrets and that was a suggested query to improve. Overall we see a benefit in reducing the number of queries, but in general we also accept specialized ones. All in all we see detecting hardcoded JWT secrets of any length eligible for bounties if not already covered by existing queries.

**Comment by luchua-bc** [comment]
Thanks @JarLob for the advice. I will check whether that's already covered by an existing Java query and will submit a new one otherwise.
