### ISSUE TITLE
Python: Add support for self attr connections and cursors for sql injections.

### ISSUE THREAD

**Issue by japroc** [github/securitylab#381]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/6023

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

- no CVEs

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

In this enhancement i want to add support for dealing with local flow to determine sql execution calls and self attribute writes and reads. For example, currently codeql does not detect db connections and cursors stored in self attribute of a class. Code snippet:
```python
class Conn:
  def __init__(self):
    self.conn = pymysql.connect(host="localhost", user="user", password="passwd")
  
  def query(self, query, params):
    cur = self.conn.cursor()
    cur.execute(query, params)  # $getSql=query
    cur.close()

classconn = Conn()
classconn.query("some sql", (42,))
```

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

Yes. I want to share my experience on upcoming conference.

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

This enhancement allows to find more sql injection vulnerabilities. Example projects:
* https://github.com/riasatullah/ZuriCapWeb
* https://github.com/dkvirus/py-novel
* https://github.com/freQuensy23-coder/CaptchServiceAPI
* https://github.com/abhiagar90/power_networks
* https://github.com/shengxinjing/woniu-cmdb
* https://github.com/EvanKaminsky/idb
* https://github.com/NinadNaik2811/flask-app-nosql-tutorial
* https://github.com/junneyang/bmemonitor
* etc...

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by JarLob** [comment]
Closing the issue in sync with the comment https://github.com/github/codeql/pull/6023#issuecomment-856844789
