### ISSUE TITLE
JS CWE-732: Overpermissive file creation

### ISSUE THREAD

**Issue by dittyroma** [github/securitylab#384]
## Query

Relevant PR: https://github.com/github/codeql/pull/6110

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

World writable resources such as config files can allow other users to control program behavior. In some cases there's code injection through the config file, which can lead to privilege elevation. World writable directories have the same weakness since they allow adding files within them. A world writable config directory `/etc/froznator/conf.d` offers a route to controlling program behavior through a new config file. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

This set of queries finds creations of world writable files and directories. It aims to detect all the major ways of specifying mode:

- Eliding mode, which uses the Node.js default that grants world write permission.
- As a literal number or string in the call.
- As a literal first transported through variables and expressions, eg by storing a program default mode.
- Constructed by setting bits. `fs.constants.S_IRWXU | fs.constants.S_IRWXG`
- Constructed by clearing bits. `0o777 & ~fs.constants.S_IRWXO`

It also detects functions which offer no way of specifying mode. These functions always use the default world writable mode and are therefore unsecurable. Query help recommends replacing these functions with securable alternatives.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

This tentative blog post describes the queries, to be finalized after code review.

https://dittyroma.wordpress.com/2021/06/17/javascript-overpermissive-file-creation/

The PR and blog post have more detailed discussion.'
'
Thank you for considering.

## Result(s)

`semver` [updated right away](https://github.com/jscutlery/semver/issues/212).

[`jspm-cli`](https://lgtm.com/projects/g/jspm/jspm-cli/snapshot/9687fe2b55caf54dd70dba190178d7cb75f200d7/files/lib/install/bin.js?sort=name&dir=ASC&mode=heatmap#L22) install creates some shell scripts world writable, allowing an attacker to control executed code.

```js
async function writeBinScripts(binDir, name, binModulePath) {
    await [new Promise((resolve, reject) => fs.writeFile(path.resolve(binDir, name), unixBin(binModulePath), {
            mode: 0o777
        }, err => err ? reject(err) : resolve())), new Promise((resolve, reject) => fs.writeFile(path.resolve(binDir, name + '.cmd'), winBin(binModulePath), {
            mode: 0o777
        }, err => err ? reject(err) : resolve()))];
}
exports.writeBinScripts = writeBinScripts;
const unixBin = (binModulePath) => `#!/bin/sh
BASE_DIR=$(dirname $(dirname $0))
JSPM_PATH=$(which jspm 2>/dev/null)
..
```

**Comment by kevinbackhouse** [comment]
@dittyroma: Did you get a CVE for any of the issues that you filed? To be honest, I think you're overhyping this with statements like "MITRE calls this CWE-732, one of the top 25 most dangerous vulnerabilities". File permissions _can_ be dangerous, but only for some files. For example, it would be bad if a root process changed the permissions of `/etc/shadow`, but if a user process creates a config file in the user's home directory with 777 permissions then that is probably entirely harmless. Your query doesn't distinguish between those two scenarios, does it?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_
