### ISSUE TITLE
[Python]: CWE-079: HTTP Header injection

### ISSUE THREAD

**Issue by jorgectf** [github/securitylab#385]
## Query

Relevant PR: https://github.com/github/codeql/pull/5463

## Report

If an HTTP Header is built using string concatenation or string formatting, and the components of the concatenation include user input, a user  is likely to be able to manipulate the response.

This query covers every way of adding headers to a `Flask`, `Django` and `Werkzeug` response and looks for user-input appended to that headers' name/value.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- [VICARA-T5](https://github.com/Crio-Winter-of-Doing-2021/VICARA-T5/tree/e043a7d3cb60a30e74dde84b82309e427686aeb7)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Generate Query Results**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1401159 for bounty 349687 : [385] [Python]: CWE-079: HTTP Header injection

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
