### ISSUE TITLE
[Python]: Add SqlAlchemy support for SQL injection query

### ISSUE THREAD

**Issue by mrthankyou** [github/securitylab#390]
## Query

Relevant PR: https://github.com/github/codeql/pull/5680

## CVE ID(s)

WIP

## Report

SQLAlchemy is one of the most popular ORM engines for working with SQL databases within the Python ecosystem. This query identifies a variety of cases where SQL injection can occur when the developer accidentally allows SQL injection to be injected into SQL queries. 

- [X] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

WIP

## Misc 

~~Please split the bounty 50/50 between myself and @jorgectf.~~ After a discussion with @jorgectf I will be taking the full bounty.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Generate Query Results**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by pwntester** [comment]
Hi @mrthankyou, Thanks for the submission,

I'm reviewing some of the results returned by this query and I can see many of them following this pattern:

```
session.query(CommonsDivision).get(commons_division_id)
```

Where `commons_division_id` is tainted. I'm not sure how this (or any other matched by the `SqlAlchemyQueryCall` sink). Can you please elaborate on why you added `SqlAlchemyQueryCall` as SQL injection sinks?

**Comment by RasmusWL** [comment]
I think it's to cover cases such as [`session.query(User).filter(sqlalchemy.sql.text(user_input))`](https://github.com/github/codeql/blob/0be2c6b7657bc1930daf5b3b86545b864dd0e8e2/python/ql/test/experimental/library-tests/frameworks/sqlalchemy/SqlExecution.py#L50), but the matching in `SqlAlchemyQueryCall` is just too broad, since [it flags the first argument to _any_ method called](https://github.com/github/codeql/blob/0be2c6b7657bc1930daf5b3b86545b864dd0e8e2/python/ql/src/experimental/semmle/python/frameworks/SqlAlchemy.qll#L82-L86). (something I overlooked while reviewing the PR)

@mrthankyou to fix this, I think you need to specify the exact method names that are vulnerable (as per your research [here](https://github.com/github/securitylab/issues/390)).

**Comment by mrthankyou** [comment]
Will do. I'll see what I can do and fix this by tomorrow. Thanks for everyones input thus far.

**Comment by mrthankyou** [comment]
Thank you for bearing with my delays.

I have updated the query so that the query only accounts for vulnerable methods discovered through this research [here](https://github.com/jty-team/codeql/pull/2#issue-611592361). Rasmus has confirmed and I ran locally that all tests still pass. Please let me know if there is anything else needed.

After next Wednesday my life will be back to normal and will be more responsive. Thank you.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1287576 for bounty 323072 : [390] [Python]: Add SqlAlchemy support for SQL injection query

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by mrthankyou** [comment]
Thanks everyone!!!
