### ISSUE TITLE
[Java] CWE-552: Query to detect configuration file/source code exposure from unsafe request dispatcher

### ISSUE THREAD

**Issue by luchua-bc** [github/securitylab#398]
## Query

*Link to pull request with your CodeQL query:*

Relevant PR: https://github.com/github/codeql/pull/6251

## CVE ID(s)

*List the CVE ID(s) associated with this vulnerability. GitHub will automatically link CVE IDs to the [GitHub Advisory Database](https://github.com/advisories).*

## Report

*Describe the vulnerability. Provide any information you think will help GitHub assess the impact your query has on the open source community.*

Directly incorporating user input into HTTP requests dispatched from the Java EE <code>RequestDispatcher</code> without validating the input can allow any web application resource such as configuration files and source code to be disclosed.

As stated in the [Java API doc](https://jakarta.ee/specifications/webprofile/9/apidocs/jakarta/servlet/servletrequest#getRequestDispatcher-java.lang.String-), when using a Java EE <code>RequestDispatcher</code>, requests may be dispatched to any part of the web application bypassing both implicit (no direct access to WEB-INF or META-INF) and explicit (defined by the web application) security constraints. Unsanitized user provided data must not be used to construct the path passed to the <code>RequestDispatcher</code> as it is very likely to create a security vulnerability in the application.

This query detects unsafe invocations of RequestDispatcher with user controlled input.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

*Provide at least one useful result found by your query, on some revision of a real project.*

- [softways-sa/swift-framework](https://github.com/softways-sa/swift-framework/)
- [Online Drug Store](https://github.com/shashankpangam/OnlineDrugStore)

**Comment by pwntester** [comment]
Hi @luchua-bc Thanks for the contribution and sorry for the radio silence as you commented on https://github.com/github/codeql/pull/6251#issuecomment-878216288 I think its better to close this PR and then open a new one when @haby0 one gets merged. Is that ok with you? if so, please close this PR.

**Comment by luchua-bc** [comment]
@pwntester Thanks for the suggestion. The @haby0 one haven't received any update for two months therefore it took much longer than I originally thought. I"m OK with closing this one first.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by luchua-bc** [comment]
As per the advice of @pwntester, I've submitted a new PR [#7286](https://github.com/github/codeql/pull/7286) to replace this one with a new issue [#495](https://github.com/github/securitylab/issues/495)
