### ISSUE TITLE
CWE-094 ScriptEngine in java

### ISSUE THREAD

**Issue by SpaceWhite** [github/securitylab#40]
## CVE ID(s)

No CVE

## Report

Using ScriptEngine in java without any protection could lead to arbitrary code execution. https://github.com/Semmle/ql/pull/2850

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Payment order sent
`Created Hackerone report 824926 for bounty 206495 : [40] CWE-094 ScriptEngine in java`
