### ISSUE TITLE
ihsinme: Add query for CWE-758 Reliance on Undefined, Unspecified, or Implementation-Defined Behavior

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#402]
## Query

Relevant PR: https://github.com/github/codeql/pull/6231

## Report

in this query I am looking for possible undefined behavior errors in expressions.
I have identified 4 main areas:

dangerous use of several incremental (decremental) operations, between sequence points.
using the functions of freeing resources.
the use of a common argument that can change the value inside the function.
the presence of a common global variable that can change its value.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- glennrp/libpng#378
- FortressOne/fteqw-code#5
- ArthurBatista04/tiger-compiler#1
- robertdavidgraham/masscan#586

**Comment by ghsecuritylab** [comment]
Your submission is now in status **FP Check**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by antonio-morales** [comment]
Hi @ihsinme,

first of all, I've to say that the query looks great :)

But I think we need a more detailed description of undefined behavior alerts. "This expression may have undefined behavior" looks very general and makes really difficult to distinguish TP from FP.

I look forward to your reply.

Regards,
Antonio.

**Comment by ihsinme** [comment]
good day @antonio-morales.

I hope you remember that the English text is not my strong point, so I will be glad to have corrections.

from what i see i can add 3 different messages
1. undefined behavior due to a possible change in the argument of a function.
2.undefined behavior due to the release of the resource
3. undefined behavior  when using cremental operations.

thanks

**Comment by ihsinme** [comment]
Good afternoon @antonio-morales.
can you missed my answer?

**Comment by kevinbackhouse** [comment]
My suggestion:
"This expression may have undefined behavior, because the order of evaluation is not specified."

Thanks for this query! I remember getting burned by this exact issue at a previous job. A test was failing, but only on macOS, because the compiler chose a different order of evaluation for the function arguments. Took a while to track the bug down because I didn't have easy access to Apple hardware at the time.

**Comment by ihsinme** [comment]
@kevinbackhouse  thanks for the help!
I made corrections.
https://github.com/github/codeql/pull/6486

**Comment by ihsinme** [comment]
Good afternoon.
tell me, maybe I need to do something for this request?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **CodeQL review**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ihsinme** [comment]
good afternoon have news on this request?

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
SecLab review > Generate Query Results > FP Check > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1345483 for bounty 335988 : [402] ihsinme: Add query for CWE-758 Reliance on Undefined, Unspecified, or Implementation-Defined Behavior
