### ISSUE TITLE
ihsinme: CPP Add a query to find incorrectly used exceptions. 

### ISSUE THREAD

**Issue by ihsinme** [github/securitylab#403]
## Query

Relevant PR: https://github.com/github/codeql/pull/6141

## Report

in this request I am looking for errors when using exceptions.
I have identified 2 main areas:
1.the ability to throw unhandled exceptions in the body of the DllMain function. from which the library code will not be unloaded.
2. creating an exception object without throwing the last one, or a rather strange construction of an exception.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

- assimp/assimp#3954
- AcademySoftwareFoundation/openexr#1059

**Comment by antonio-morales** [comment]
Hi @ihsinme,

in order to meet the new submission criteria, you need to support your submission with a CVE mapping (old or new) not previously covered by any existing CodeQL query. See https://securitylab.github.com/bounties for more details.

Can you link your results to a CVE?

Thanks,
Antonio.

**Comment by ihsinme** [comment]
Hi @antonio-morales

changes in the rules regarding cve only appeared today.
I have no experience in this area yet, and I was hoping that applications submitted before the changes were made will be processed according to the old rules.

In general, it would be great if you could apply the old rules and queries that would be generated based on the PR filed before your changes.

But according to the rules of the reward program, you can do it as you see fit.
I will wait for your reply.

**Comment by ihsinme** [comment]
Good afternoon @antonio-morales.
can you missed my answer?

**Comment by ihsinme** [comment]
Good afternoon.

I have not received an answer to my question about the need for cve in requests that were generated before the changes to the program.

and also for those requests that would have been created on the basis of PR, which were submitted earlier than the changes in the program.

**Comment by ihsinme** [comment]
I still haven't received an answer to my question?

**Comment by ihsinme** [comment]
ping

**Comment by ihsinme** [comment]
Good afternoon.
3 months have passed since my question.
I don't understand why there is no answer.
tell me what I'm doing wrong.

**Comment by antonio-morales** [comment]
hi @ihsinme 

Unfortunately, we need a valid CVE in order to accept your submission.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Test run**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by JarLob** [comment]
Looking at the [results](https://lgtm.com/query/7864086823722766951/) in the [PR](https://github.com/github/codeql/pull/6141) I think most of the results from `facebook/folly` are false positives like `makeSystemErrorExplicit` which looks like a factory method for exceptions. While the result in `Shervanator/Engine` looks like true positive since an exception is just created on the stack.
Would it make sense to exclude all functions that **return** the exception?

**Comment by ihsinme** [comment]
good day @JarLob 
Thanks.
interesting FP, I'll fix it.

**Comment by ihsinme** [comment]
https://github.com/github/codeql/pull/7177

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Query review**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1455531 for bounty 362792 : [403] ihsinme: CPP Add a query to find incorrectly used exceptions.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ihsinme** [comment]
thanks
