### ISSUE TITLE
PYTHON: CWE-079 - Add query for email injection

### ISSUE THREAD

**Issue by mrthankyou** [github/securitylab#476]
## Query

Relevant PR: https://github.com/github/codeql/pull/7127

## CVE ID(s)

WIP

## Report

This query looks for Python applications that are exposed to sending malicous emails containing reflective XSS. Python applications utilize various email libraries to generate emails. If at any time an email is generated in such a way that user input taints the HTML body of the email, then the user can craft malicious emails that render reflective XSS onto the recipient of the email. 

It's normally expected that developers should either sanitize the user input before passing it into the HTML body or not pass user input altogether.

- [X] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

WIP

## Anything Else We Should Know 
Please give 100% of the bounty reward to @jorgectf.

**Comment by JarLob** [comment]
Hi, the CVE is marked as WIP. Any update on it?

**Comment by mrthankyou** [comment]
We are still working with one team on a CVE. We will update you guys once we have something.

**Comment by jorgectf** [comment]
The advisory has been published! https://github.com/OriginProtocol/origin-website/security/advisories/GHSA-v6fc-qwxx-m4h7

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Test run**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Results analysis**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 1602237 for bounty 398648 : [476] PYTHON: CWE-079 - Add query for email injection

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
