### ISSUE TITLE
[Python] CWE-614: Cookie security-related queries

### ISSUE THREAD

**Issue by jorgectf** [github/securitylab#479]
## Query

Relevant PR: https://github.com/github/codeql/pull/6360

## CVE ID(s)

WIP

## Report

Constructing cookies from user input may allow an attacker to perform a Cookie Poisoning attack. It is possible, however, to perform other parameter-like attacks through cookie poisoning techniques, such as SQL Injection, Directory Traversal, or Stealth Commanding, etc.

Furthermore, this query set covers the misconfiguration of security-related flags like `httponly`, `secure` and `samesite`.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

## Result(s)

WIP

**Comment by JarLob** [comment]
Hi @jorgectf,
Does the query detect any known CVE?

**Comment by jorgectf** [comment]
> Hi @jorgectf, Does the query detect any known CVE?

I'm currently working on it :)

**Comment by jorgectf** [comment]
@JarLob It doesn't seem there are [many CVEs](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=cookie+injection+python) regarding cookie injection in python (at least that I can find). Although cookie injection is an entrypoint for many vulnerabilities (like the huge amount of SQLis through cookies in PHP that can be seen in the previous link), I'd find closing this issue fair enough as per the bounty policy.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
