### ISSUE TITLE
CPP: Out of order Linux permission dropping without checking return codes

### ISSUE THREAD

**Issue by theopolis** [github/securitylab#50]
The query in targeting an `experimental` folder in `ql`: https://github.com/Semmle/ql/pull/3002 and the original feedback and design discussion: https://github.com/github/securitylab/pull/37

## CVE ID(s)

No CVEs as these bugs are in defense-in-depth and best-practice strategies.

- Lightning-fast improvements from LXC lxc/lxc#3265
- True-positive and fixed swaywm/sway#4990
- True-positive and fixed DNS-OARC/dnscap#208
- Created an issue, I will try to follow up (confirm impact/write PR) later: darkk/redsocks#149

## Report

[POS37-C. Ensure that privilege relinquishment is successful](https://wiki.sei.cmu.edu/confluence/display/c/POS37-C.+Ensure+that+privilege+relinquishment+is+successfu) style bugs are particularly concerning when the permissions dropping is "out of order". In this context "out of order" means the user permissions are dropped first and subsequent calls to `setgroups`, `initgroups` or `setgid`-like functions will fail because the new effective user does not have permissions.

> - [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc)

Nope.

**Comment by theopolis** [comment]
Hi folks, checking in on the status of this issue. Anything else you need from me?

**Comment by xcorail** [comment]
Created Hackerone report 852349 for bounty 212059 : [50] CPP: Out of order Linux permission dropping without checking return codes

**Comment by theopolis** [comment]
Thanks again for the bounty, my goal was to use the awards to donate to various COVID-19 response funds. HackerOne was able to set up these donations (to a specific fund run by a charity) easily, that flexibility is impressive!
