### ISSUE TITLE
Go/CWE-643: XPath Injection Query in Go

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/securitylab#52]
## CVE ID(s)

- None

## Report

[OWASP on XPath Injection](https://owasp.org/www-community/attacks/XPATH_Injection):
> XPath Injection attacks occur when a web site uses user-supplied information to construct an XPath query for XML data. By sending intentionally malformed information into the web site, an attacker can find out how the XML data is structured, or access data that he may not normally have access to.

https://github.com/github/codeql-go/pull/66

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by intrigus-lgtm** [comment]
PR, that makes the query supported: https://github.com/github/codeql-go/pull/73

**Comment by intrigus-lgtm** [comment]
All merged :)

**Comment by xcorail** [comment]
Created Hackerone report 852316 for bounty 212050 : [52] Go/CWE-643: XPath Injection Query in Go 🎉
