### ISSUE TITLE
[java]: query to detect CORS misconfiguration

### ISSUE THREAD

**Issue by ahmed532009** [github/securitylab#520]
### Query PR

https://github.com/github/codeql/pull/7563

### Language

Java

### CVE(s) ID list

None

### CWE

CWE-346

### Report

the <a href="https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy">Same origin policy</a> is an important security feature of any modern browser. Its purpose is to restrict cross-origin interactions between documents, scripts, or media files from one origin to a web page with a different origin. The requested target can append additional HTTP headers in response, called <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS">CORS</a>,
that act like directives for the browser and change the access control policy / relax the same origin policy.

Computing this header value from information in the request to the server can therefore potentially allow an attacker to control,
the origins that the browser sends credentials to.

The query finds the following in tomcat web.xml file  :

* <code>Access-Control-Allow-Origin</code> being set to '*' along with <code>Access-Control-Allow-Credentials</code> set to true.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by JarLob** [comment]
Hello,
Thank you for your submission.
1. According to the [rules](https://securitylab.github.com/bounties/) to be considered your query must successfully detect any previously disclosed CVE. However there is no CVE number provided.
2. Browsers [do not send credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#:~:text=Attempting%20to%20use%20the%20wildcard%20with%20credentials%20results%20in%20an%20error.) when `Access-Control-Allow-Origin` is set to *.

The query in current state is not eligible for a bounty.

**Comment by ahmed532009** [comment]
hello, sorry for the delay.
* There's no CVE for this, This is more like a bad security pattern being set. 
Similar to what i said  in this query https://github.com/github/securitylab/issues/248 

*  the query find the following <code>Access-Control-Allow-Origin</code> is set to *, along with <code>Access-Control-Allow-Credentials</code> set to true. this configuration can give the attacker the ability to steal user informations

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ahmed532009** [comment]
t/
