### ISSUE TITLE
CPP: Out of order Linux permission dropping without checking return codes

### ISSUE THREAD

**Issue by theopolis** [github/securitylab#57]
See https://github.com/github/securitylab/issues/50 for the bugs found and fixed, as well as a description of the bug and example fixing strategies.

Here is the query merged into an `experimental` folder: https://github.com/Semmle/ql/pull/3002

The precision is fairly good, and next steps are reviewing the new supported-queries documentation and working to get it out of experimental.

**Comment by theopolis** [comment]
Hi folks, checking in on the status of this issue. Anything else you need from me?

**Comment by xcorail** [comment]
Hi @theopolis 
the team is currently scoring the submission
Thanks for your patience!

**Comment by xcorail** [comment]
Created Hackerone report 845729 for bounty 210700 : [57] CPP: Out of order Linux permission dropping without checking return codes
