### ISSUE TITLE
CodeQL query to detect OGNL injections

### ISSUE THREAD

**Issue by ggolawski** [github/securitylab#69]
## CVE ID(s)

There's no CVE for this.

## Report

I created a query to detect OGNL injections in Java code. The query raises a flag if user-provided OGNL expression is evaluated. OGNL library and Struts2 (`OgnlUtil` class) are supported.

The details are present in PR: https://github.com/Semmle/ql/pull/3294

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Created Hackerone report 917455 for bounty 227492 : [69] CodeQL query to detect OGNL injections 🎉

**Comment by ggolawski** [comment]
Thanks @xcorail!
