### ISSUE TITLE
CodeQL query to detect Unified EL injections

### ISSUE THREAD

**Issue by ggolawski** [github/securitylab#71]
## CVE ID(s)

There's no CVE for this.

## Report

I created a query to detect Unified EL (`javax.el`) injections in Java code. The query raises a flag if user-provided expression is evaluated. `ExpressionFactory.createValueExpression`, `ExpressionFactory.createMethodExpression` and `ELProcessor` are supported.

The details are present in PR: https://github.com/Semmle/ql/pull/3323
- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by xcorail** [comment]
Hi @ggolawski ,

Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query does not catch any true positive and is therefore not eligible for a reward under the Bug Bounty program. 

Looking forward to your next submissions!

Best regards and happy hacking!
