### ISSUE TITLE
[python] TarSlip vulnerability improvements

### ISSUE THREAD

**Issue by Sim4n6** [github/securitylab#710]
### Query PR

https://github.com/github/codeql/pull/10851 (closed in favor of the next one)
https://github.com/github/codeql/pull/10887

### Language

Python

### CVE(s) ID list

- https://huntr.dev/bounties/2d1db3c9-93e8-4902-a55b-5ea53c22aa11/
- https://huntr.dev/bounties/309725a2-bfc9-4ef3-a4c1-360a9f6b890b/
more to come.

### CWE

CWE-022

### Report

1. TarSlip vulnerability.
2. _Extracting files from a malicious tarball without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten, due to the possible presence of directory traversal elements (<code>..</code>) in archive path names.
3. I have added more sources and sinks than I checked the combination use of both.
4. Yes, I've checked the query against valid samples extracted from https://cs.github.com. I ethically reported them using https://huntr.dev (more to become public soon).  
5. This is my first contribution, and I would love to provide more. 

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

### Blog post link

https://www.getrevue.co/profile/sim4n6

https://github.com/github/securitylab/issues/710#tasklist-block-5abb13fc-c5a6-4f9d-8f50-0796b88642d3

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Test run**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Query review**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Results analysis**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by Sim4n6** [comment]
Re-adapted the PR into this one: https://github.com/github/codeql/pull/10887

**Comment by Sim4n6** [comment]
PR merged https://github.com/github/codeql/pull/10887 💯

**Comment by Sim4n6** [comment]
Any update related to this issue, please? 🙃

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Final decision**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Hello @Sim4n6 
Can you please provide a public email address, or send me privately a private one?
Thanks

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by Sim4n6** [comment]
Sim4n6@gmail.com

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by Sim4n6** [comment]
Thank you very much.
