### ISSUE TITLE
Go: Add modelling for `gorqlite` and `GoFrame` frameworks 

### ISSUE THREAD

**Issue by ghost** [github/securitylab#723]
### Query PR

https://github.com/github/codeql/pull/9779

### Language

GoLang

### CVE(s) ID list

[alexedwards/scs](https://www.huntr.dev/bounties/fa7caf37-7fe7-4c22-80eb-3a3daee7eb5a/)

### CWE

CWE-89: SQL Injection

### Report

The  PR improves the existing modelling for Go's SQL injection query. It adds modelling for [`gogf`](https://github.com/gogf/gf)(8.7k stars) and [`gorqlite`](https://github.com/rqlite/gorqlite)(87 stars) frameworks.

There is atleast one CVE detected by this query. There should be more detected but given ongoing issue with rate limits on MRVA, I am unable to test my query at scale.

The original project needs some work to be correctly build and detect the vulnerability. I am attaching a database with a trimmed down version of the vulnerable project to show successful detection. 

[scsDb.zip](https://github.com/github/securitylab/files/10422686/scsDb.zip)

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [ ] Yes
- [ ] No

**Comment by p-** [comment]
Hello @porcupineyhairs 
We were not able to verify with the maintainer of scs if a CVE should be assigned to this vulnerability.
Basically, there are now two options: you could ask huntr.dev if they can assign a CVE for [this issue](https://www.huntr.dev/bounties/fa7caf37-7fe7-4c22-80eb-3a3daee7eb5a/) ([huntr.dev is a CNA](https://www.cve.org/PartnerInformation/ListofPartners/partner/@huntrdev)). Alternatively, you could ask Mitre if they would assign a CVE for it.
(The last option of course would be to search for another vulnerability using this query where a CVE can be assigned.)

**Comment by p-** [comment]
Hi @porcupineyhairs 
I will discuss this with the team. From my current/initial point of view it might make more sense if the PR for [DSN Injection](https://github.com/github/codeql/pull/12901) would be submitted as a new bounty submission?
(But yes if you're worried about the scope we might have a look at it both ways).

As to the answer from MITRE:
```
As far as we can tell, SQL injection was only in rqlite, which
was experimental code that was never released in any SCS version.
The code was added in:

  https://github.com/alexedwards/scs/commit/b95d685652e43a5e3662740fa627fec2f21079ab

and then soon deleted in:

  https://github.com/alexedwards/scs/commit/d93ace5be94bc476d79a2b818ae6579fa76e5a59

Because it was never released, there is no CVE ID.
```

This sounds reasonable to me and resembles the experience of finding no further TPs with these additions. Of course this doesn't mean that your initial additions are worthless, it just might mean that your initial additions are not eligible for a bounty payout.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
