### ISSUE TITLE
[C#]: DOS through Decompression

### ISSUE THREAD

**Issue by am0o0** [github/securitylab#778]
### Query PR

https://github.com/github/codeql/pull/13558

### Language

C#

### CVE(s) ID list

- no CVE yet and definitely a CVE will be published soon.

### Report

Extracting Compressed files with any compression algorithm like gzip can cause to denial of service attacks. Attackers can compress a huge file which created by repeated similar byte and convert it to a small compressed file.
Added modeling for multiple CLI third parties.
In this pull request I've also added some valuable remote flow sources which I thought it is related to my query because mostly it need a file upload from Forms as a User Remote Source.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by Kwstubbs** [comment]
@am0o0 how goes finding the CVE for this? If you do, please include the database as well

**Comment by Kwstubbs** [comment]
alright thanks

**Comment by xcorail** [comment]
Closing upon request from @am0o0

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
