### ISSUE TITLE
CodeQL query for disabled revocation checking

### ISSUE THREAD

**Issue by artem-smotrakov** [github/securitylab#78]
## CVE ID(s)

The query found several places in Apache CXF and Cloudstack where certificate revocation checking was disabled:

- https://github.com/apache/cxf/commit/e4b7097b19388124883191bc32300ee6562849b4
- https://github.com/apache/cxf/commit/a1b0abe02b943ff43fed5020643ce3b2ccebb12f
- https://github.com/apache/cloudstack/pull/4065

## Report

I added a query that looks for disabled revocation checking in Java, please see https://github.com/github/codeql/pull/3436

Using a revoked certificate may be dangerous. One of the most common reasons why a certificate authority (CA) revokes a certificate is that the private key has been compromised. For example, the private key might have been stolen by an adversary.

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

I am planning to write a blog post about the query I wrote and catching such issues with CodeQL.

**Comment by anticomputer** [comment]
GHSL feedback: this query has a confirmed low false positive rate with a practical scope across a variety of projects as verified on LGTM. Security impact is application context dependent.

**Comment by xcorail** [comment]
Created Hackerone report 917453 for bounty 227490 : [78] CodeQL query for disabled revocation checking 🎉
