### ISSUE TITLE
CodeQL query for unsafe TLS versions

### ISSUE THREAD

**Issue by artem-smotrakov** [github/securitylab#79]
## CVE ID(s)

- [https://issues.apache.org/jira/browse/GEODE-8070](GEODE-8070) (the issue was recently found but the query catches it as well)

## Report

I added a query that looks for unsafe TLS versions in Java, please see https://github.com/github/codeql/pull/3438

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

I am planning to write a blog post about the query and catching such issues with CodeQL.

**Comment by xcorail** [comment]
Created Hackerone report 894871 for bounty 222044 : [79] CodeQL query for unsafe TLS versions
🎉
