### ISSUE TITLE
[JS]: Signing and verifying JWT signature with a constant key

### ISSUE THREAD

**Issue by am0o0** [github/securitylab#799]
### Query PR

https://github.com/github/codeql/pull/14666

### Language

Javascript

### CVE(s) ID list

WIP

### CWE

CWE-798

### Report

Usage of a hardcoded secret key to decode and verify JWTs will cause authentication and authorization bypass which in this query I tried to model many libraries for.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by p-** [comment]
Hey @amammad 👋 
Just a reminder that a CVE is missing here.

**Comment by p-** [comment]
>Hi Peter, Is there any deadline for finding a new/old CVE?

No, afaik there's not. (but of course a reasonable time frame is welcome)

**Comment by p-** [comment]
Hey @am0o0 
some time has passed by already, have you found a CVE for this issue by coincidence?

**Comment by p-** [comment]
>I'll try this weekend again, maybe I found a new repository that is worth it.

👍 

>do you accept this as I have to disclose the vulnerability in PR?

Let's wait if your new attempts bear any fruits and then I can talk to the team about that. (But in general we have the CVE requirement)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Results analysis**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 2653385 for bounty 607088 : [799] [JS]: Signing and verifying JWT signature with a constant key
