### ISSUE TITLE
[Java] CWE-918: Query for server side request forgery (SSRF) detection

### ISSUE THREAD

**Issue by ghost** [github/securitylab#80]
## CVE ID(s)

None

## Report

If network request are made using `java.net.URL` constructed directly from a user-provided value, an attacker might be able to bypass security restrictions such as external firewalls and execute request on internal services by providing URLs like `http://127.0.0.1:8081/admin`

Related pull request:
[github/codeql#3452](https://github.com/github/codeql/pull/3452)

- [x] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query is not eligible for a reward under the Bug Bounty program for the following reason: Duplicate submission, PR rejected,

Best regards and happy hacking!

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
