### ISSUE TITLE
[Kotlin]: Add support for Ktor framework

### ISSUE THREAD

**Issue by am0o0** [github/securitylab#805]
### Query PR

https://github.com/github/codeql/pull/14959

### Language

Java

### CVE(s) ID list

WIP

### Report

I tried to support the whole framework both the client side and server side.
the scope of SSRF, user-controllable sources, XSS,  Unsafe LDAP, and Sensitive APIs (hard coded secret) has been extended by this submission, this is the biggest and most used web framework written in Kotlin, and I hope it is a useful extension for all.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by xcorail** [comment]
Closing upon request from @am0o0

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
Initial triage > Test run > Results analysis > Query review > Final decision > Pay > Closed_
