### ISSUE TITLE
gagliardetto: Query to detect incorrect conversion between numeric types

### ISSUE THREAD

**Issue by gagliardetto** [github/securitylab#82]
## CVE ID(s)

There's no CVE for this.

## Report

- The PR of the query (merged): https://github.com/github/codeql-go/pull/116 

- Short summary: The query models a particular case of [CWE-681: Incorrect Conversion between Numeric Types](https://cwe.mitre.org/data/definitions/681.html).

- See the PR for bug description, and the `qhelp` file for remediation guidelines: https://github.com/github/codeql-go/blob/master/ql/src/experimental/CWE-681/IncorrectNumericConversion.qhelp

- Inspiration: https://github.com/kubernetes/kubernetes/issues/81121

- [ ] Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc). *We would love to have you spread the word about the good work you are doing*

This might become part of a wider-scoped article on Golang standard-library bugs.

**Comment by xcorail** [comment]
Hey @gagliardetto 
Can you please provide a public email, or send your email privately to me?
Thanks

**Comment by gagliardetto** [comment]
Hey @xcorail 

Thanks for getting back to me on this! I sent you an email to the address listed on your GitHub profile.

**Comment by xcorail** [comment]
Created Hackerone report 891265 for bounty 221135 : [82] gagliardetto: Query to detect incorrect conversion between numeric types
🎉

**Comment by gagliardetto** [comment]
Thank you very much!

Now I have a great :sparkles: excuse :sparkles: with myself to justify dedicating more time to codeql :star_struck:
