### ISSUE TITLE
C#: Add query for insecure certificate validation

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/securitylab#838]
### Query PR

https://github.com/github/codeql/pull/16824

### Language

C#

### CVE(s) ID list

CVE in disclosure process

### CWE

CWE-295

### Report

If a `RemoteCertificateValidationCallback` delegate always returns `true` and is used in e.g. `ServicePointManager.ServerCertificateValidationCallback`, it trusts any certificate.
As the RemoteCertificateValidationCallback trusts any certificate, an attacker can create a self-signed certificate that will be accepted as any certificate is trusted. This leads to a MiTM attack against the connection thereby stealing sensitive secrets such as login data or other tokens is possible.

### Are you planning to discuss this vulnerability submission publicly? (Blog Post, social networks, etc).

- [X] Yes
- [ ] No

**Comment by xcorail** [comment]
Created Hackerone report 2817126 for bounty 635269 : [838] C#: Add query for insecure certificate validation

**Comment by xcorail** [comment]
Hey @intrigus-lgtm don't forget to claim your reward, the program is shutting down soon!
