### ISSUE TITLE
Java : add MongoDB injection sinks

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#95]
# CVE

There is no CVE for this. 

# Report

This query adds MongoDB NoSQL injection sinks. It models the official mongodb-java driver.

It detects the following code patterns.
```java
DBObject databaseQuery = (DBObject) JSON.parse('sink');
```
and 
```java
BasicDBObject bdb = BasicDBObject.parse('sink');
```

Link to the PR:[github/codeql#3542]

**Comment by porcupineyhairs** [comment]
I can't find a CVE for this. However, I can see this being found in an intentionally vulnerable application [here](https://github.com/shirishp/NoSQLInjectionDemo/blob/0108570ac4f947b36f95f5ced637179271c0c724/src/main/java/nosql/injection/demo/model/NoSQLDatabase.java#L21-L33)

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Pay**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 983867 for bounty 245674 : [95] Java : add MongoDB injection sinks 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_
