### ISSUE TITLE
Golang : Improvements to Golang SSRF query

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#97]
# CVE 

This query has not been tested against all lgtm projects. So, there is no CVE found using this PR.

# Report

This query detects instances where untrusted user input may be used to instantiate a server side connection to an attacker controlled node. This query adds websocket sinks for the following 3rd party libraries.

1. [gorilla websocket](https://github.com/gorilla/websocket) (11.7k stars)
2. [golang/x/net/websocket](https://github.com/golang/net/tree/master/websocket) (2.1k stars)
3. [gobwas websocket](https://github.com/gobwas/ws) (3.1k stars)
4. [nhooyr.io websocket](https://github.com/nhooyr/websocket) (1.3k stars)

Apart from these,  the initial version of this PR also included support for the `net/http` standard library's `Do/ Get/ Post ` etc. methods. These were afterwards removed as there was an existing query detecting SSRF which included these sinks.

This query also added checks for three type of sanitizers. All of them based on the OpenURL redirect query.
1. An equality check of the form
 `
if input == "localhost"{
   //sink 
}
`
2. A regex check 
`
if m, _ := regexp.MatchString("ws://localhost:12345/*", untrustedInput); m {
 // sink 
}
`
3. A function of the form `isLocalUrl`, `isValidRedirect`.

The now merged [PR](github/codeql-go#107) also include library tests as well as query tests and a qhelp file along with well documented code.

Link to the PR:[github/codeql-go#107]

**Comment by porcupineyhairs** [comment]
I can't find a golang cve for this. However, I did come across [this issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/56271) which is very similar to what this query detects. I can see a comment claiming that a request param is used for initiating a WebSocket connection. But it is difficult to say for sure as the corresponding h1 report and PR are non public.

**Comment by ghsecuritylab** [comment]
Your submission is now in status **SecLab finalize**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by xcorail** [comment]
Created Hackerone report 956296 for bounty 237619 : [97] Golang : Improvements to Golang SSRF query 🎉

**Comment by ghsecuritylab** [comment]
Your submission is now in status **Closed**.

_For information, the evaluation workflow is the following:
CodeQL initial assessment > SecLab review > CodeQL review > SecLab finalize > Pay > Closed_

**Comment by porcupineyhairs** [comment]
Thanks a lot for the bounty!!
