### ISSUE TITLE
Golang : Add MongoDb NoSQL injection sinks

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#98]
# CVE

There is no CVE for this. 

# Report

This query adds MongoDB NoSQL injection sinks to the existing SQl injection query.

Link to the now merged PR:[github/codeql-go#130]

**Comment by porcupineyhairs** [comment]
I can't find any cve which corressponds to this. Also, the eval didn't give any results so I am self closing this issue as this is ineligible for bounty.

**Comment by anticomputer** [comment]
@porcupineyhairs we were able to find a viable result set with this query, so this is still under active evaluation :)

**Comment by anticomputer** [comment]
For clarity: we are evaluating a diff of the additional results your added sinks yield. The minimal requirement is to find a TP or match a given CVE, so this is still in the running for award.

**Comment by porcupineyhairs** [comment]
@anticomputer I can see Max's  comments [here](https://github.com/github/codeql-go/pull/130#pullrequestreview-410712878) that the eval showed no result changes. Hence I closed this issue.

**Comment by sauyon** [comment]
Those are our internal evaluations (dist-compare) and are separate from the runs on LGTM.

**Comment by porcupineyhairs** [comment]
@sauyon I didn't know that. Thanks.

**Comment by xcorail** [comment]
Created Hackerone report 909375 for bounty 225683 : [98] Golang : Add MongoDb NoSQL injection sinks
🎉
