### ISSUE TITLE
Golang : Improvements to existing TaintTracking configuration

### ISSUE THREAD

**Issue by porcupineyhairs** [github/securitylab#99]
# CVE
There is no CVE for this.

# Report

This [PR](github/codeql-go#131) models the golang `stdlib` io package. Before this PR was merged, the CodeQL-go taint-tracking configuration could not recognize flow through function in the Golang standard library's `io` module. That meant a flow of the following type could not be tracked.

```go
 _, reader, _ := n.Reader(context.TODO()) 
 writer, _ := n.Writer(context.TODO(), 0) 
 io.Copy(writer, reader) 
```

Tracking flow of this type was necessitated by two other PR's github/codeql-go#108 and  github/codeql-go#109

With this merged, taint tracking can now track flow through readers and writers.

Link to the now merged PR:[github/codeql-go#131]

**Comment by xcorail** [comment]
Hi @porcupineyhairs ,

Thanks for the submission! We have reviewed your report and validated your findings. After internally assessing the findings and the query we have determined this query is not eligible for a reward under the Bug Bounty program, as it doesn't by itself detect bugs, but supports other such queries. As stated in our official rules, 
> Queries must meet at least the requirements for experimental queries, including at least one useful result on some revision of a real project.

This improvement to the taint tracking library is however very useful, including for the rest of the community, and we'll make sure to take this submission into account when we score your other submissions that depend on this one.

Best regards and happy hacking!
